//###########################################################################
//
// FILE:    pmbus_command_indexes.c
//
// TITLE:
//
// NOTES:
//  1)
//###########################################################################
//
//  Ver  | dd mmm yyyy | Who  		| Description of changes
// ======|=============|============|========================================
//  00 	   08 28 2015 	 HPCS
//
//  Texas Instruments, Inc
//  Copyright Texas Instruments 2008. All rights reserved.
//###########################################################################

#include "system_defines.h"
#include "cyclone_device.h"
#include "variables.h"
#include "function_definitions.h"
#include "software_interrupts.h"
#include "pmbus_common.h"
#include "pmbus_topology.h"



#if PMBUS_CMD_00_ENABLE
    #define PMBUS_CMD_00_INDEX (1)
#else
    #define PMBUS_CMD_00_INDEX (0)
#endif



#define PMBUS_CMD_01_COUNT (PMBUS_CMD_00_ENABLE + PMBUS_CMD_01_ENABLE)

#if PMBUS_CMD_01_ENABLE
    #define PMBUS_CMD_01_INDEX (PMBUS_CMD_01_COUNT)
#else
    #define PMBUS_CMD_01_INDEX (0)
#endif

#define PMBUS_CMD_02_COUNT (PMBUS_CMD_01_COUNT + PMBUS_CMD_02_ENABLE)

#if PMBUS_CMD_02_ENABLE
    #define PMBUS_CMD_02_INDEX (PMBUS_CMD_02_COUNT)
#else
    #define PMBUS_CMD_02_INDEX (0)
#endif

#define PMBUS_CMD_03_COUNT (PMBUS_CMD_02_COUNT + PMBUS_CMD_03_ENABLE)

#if PMBUS_CMD_03_ENABLE
    #define PMBUS_CMD_03_INDEX (PMBUS_CMD_03_COUNT)
#else
    #define PMBUS_CMD_03_INDEX (0)
#endif

#define PMBUS_CMD_04_COUNT (PMBUS_CMD_03_COUNT + PMBUS_CMD_04_ENABLE)

#if PMBUS_CMD_04_ENABLE
    #define PMBUS_CMD_04_INDEX (PMBUS_CMD_04_COUNT)
#else
    #define PMBUS_CMD_04_INDEX (0)
#endif

#define PMBUS_CMD_05_COUNT (PMBUS_CMD_04_COUNT + PMBUS_CMD_05_ENABLE)

#if PMBUS_CMD_05_ENABLE
    #define PMBUS_CMD_05_INDEX (PMBUS_CMD_05_COUNT)
#else
    #define PMBUS_CMD_05_INDEX (0)
#endif

#define PMBUS_CMD_06_COUNT (PMBUS_CMD_05_COUNT + PMBUS_CMD_06_ENABLE)

#if PMBUS_CMD_06_ENABLE
    #define PMBUS_CMD_06_INDEX (PMBUS_CMD_06_COUNT)
#else
    #define PMBUS_CMD_06_INDEX (0)
#endif

#define PMBUS_CMD_07_COUNT (PMBUS_CMD_06_COUNT + PMBUS_CMD_07_ENABLE)

#if PMBUS_CMD_07_ENABLE
    #define PMBUS_CMD_07_INDEX (PMBUS_CMD_07_COUNT)
#else
    #define PMBUS_CMD_07_INDEX (0)
#endif

#define PMBUS_CMD_08_COUNT (PMBUS_CMD_07_COUNT + PMBUS_CMD_08_ENABLE)

#if PMBUS_CMD_08_ENABLE
    #define PMBUS_CMD_08_INDEX (PMBUS_CMD_08_COUNT)
#else
    #define PMBUS_CMD_08_INDEX (0)
#endif

#define PMBUS_CMD_09_COUNT (PMBUS_CMD_08_COUNT + PMBUS_CMD_09_ENABLE)

#if PMBUS_CMD_09_ENABLE
    #define PMBUS_CMD_09_INDEX (PMBUS_CMD_09_COUNT)
#else
    #define PMBUS_CMD_09_INDEX (0)
#endif

#define PMBUS_CMD_0A_COUNT (PMBUS_CMD_09_COUNT + PMBUS_CMD_0A_ENABLE)

#if PMBUS_CMD_0A_ENABLE
    #define PMBUS_CMD_0A_INDEX (PMBUS_CMD_0A_COUNT)
#else
    #define PMBUS_CMD_0A_INDEX (0)
#endif

#define PMBUS_CMD_0B_COUNT (PMBUS_CMD_0A_COUNT + PMBUS_CMD_0B_ENABLE)

#if PMBUS_CMD_0B_ENABLE
    #define PMBUS_CMD_0B_INDEX (PMBUS_CMD_0B_COUNT)
#else
    #define PMBUS_CMD_0B_INDEX (0)
#endif

#define PMBUS_CMD_0C_COUNT (PMBUS_CMD_0B_COUNT + PMBUS_CMD_0C_ENABLE)

#if PMBUS_CMD_0C_ENABLE
    #define PMBUS_CMD_0C_INDEX (PMBUS_CMD_0C_COUNT)
#else
    #define PMBUS_CMD_0C_INDEX (0)
#endif

#define PMBUS_CMD_0D_COUNT (PMBUS_CMD_0C_COUNT + PMBUS_CMD_0D_ENABLE)

#if PMBUS_CMD_0D_ENABLE
    #define PMBUS_CMD_0D_INDEX (PMBUS_CMD_0D_COUNT)
#else
    #define PMBUS_CMD_0D_INDEX (0)
#endif

#define PMBUS_CMD_0E_COUNT (PMBUS_CMD_0D_COUNT + PMBUS_CMD_0E_ENABLE)

#if PMBUS_CMD_0E_ENABLE
    #define PMBUS_CMD_0E_INDEX (PMBUS_CMD_0E_COUNT)
#else
    #define PMBUS_CMD_0E_INDEX (0)
#endif

#define PMBUS_CMD_0F_COUNT (PMBUS_CMD_0E_COUNT + PMBUS_CMD_0F_ENABLE)

#if PMBUS_CMD_0F_ENABLE
    #define PMBUS_CMD_0F_INDEX (PMBUS_CMD_0F_COUNT)
#else
    #define PMBUS_CMD_0F_INDEX (0)
#endif

#define PMBUS_CMD_10_COUNT (PMBUS_CMD_0F_COUNT + PMBUS_CMD_10_ENABLE)

#if PMBUS_CMD_10_ENABLE
    #define PMBUS_CMD_10_INDEX (PMBUS_CMD_10_COUNT)
#else
    #define PMBUS_CMD_10_INDEX (0)
#endif

#define PMBUS_CMD_11_COUNT (PMBUS_CMD_10_COUNT + PMBUS_CMD_11_ENABLE)

#if PMBUS_CMD_11_ENABLE
    #define PMBUS_CMD_11_INDEX (PMBUS_CMD_11_COUNT)
#else
    #define PMBUS_CMD_11_INDEX (0)
#endif

#define PMBUS_CMD_12_COUNT (PMBUS_CMD_11_COUNT + PMBUS_CMD_12_ENABLE)

#if PMBUS_CMD_12_ENABLE
    #define PMBUS_CMD_12_INDEX (PMBUS_CMD_12_COUNT)
#else
    #define PMBUS_CMD_12_INDEX (0)
#endif

#define PMBUS_CMD_13_COUNT (PMBUS_CMD_12_COUNT + PMBUS_CMD_13_ENABLE)

#if PMBUS_CMD_13_ENABLE
    #define PMBUS_CMD_13_INDEX (PMBUS_CMD_13_COUNT)
#else
    #define PMBUS_CMD_13_INDEX (0)
#endif

#define PMBUS_CMD_14_COUNT (PMBUS_CMD_13_COUNT + PMBUS_CMD_14_ENABLE)

#if PMBUS_CMD_14_ENABLE
    #define PMBUS_CMD_14_INDEX (PMBUS_CMD_14_COUNT)
#else
    #define PMBUS_CMD_14_INDEX (0)
#endif

#define PMBUS_CMD_15_COUNT (PMBUS_CMD_14_COUNT + PMBUS_CMD_15_ENABLE)

#if PMBUS_CMD_15_ENABLE
    #define PMBUS_CMD_15_INDEX (PMBUS_CMD_15_COUNT)
#else
    #define PMBUS_CMD_15_INDEX (0)
#endif

#define PMBUS_CMD_16_COUNT (PMBUS_CMD_15_COUNT + PMBUS_CMD_16_ENABLE)

#if PMBUS_CMD_16_ENABLE
    #define PMBUS_CMD_16_INDEX (PMBUS_CMD_16_COUNT)
#else
    #define PMBUS_CMD_16_INDEX (0)
#endif

#define PMBUS_CMD_17_COUNT (PMBUS_CMD_16_COUNT + PMBUS_CMD_17_ENABLE)

#if PMBUS_CMD_17_ENABLE
    #define PMBUS_CMD_17_INDEX (PMBUS_CMD_17_COUNT)
#else
    #define PMBUS_CMD_17_INDEX (0)
#endif

#define PMBUS_CMD_18_COUNT (PMBUS_CMD_17_COUNT + PMBUS_CMD_18_ENABLE)

#if PMBUS_CMD_18_ENABLE
    #define PMBUS_CMD_18_INDEX (PMBUS_CMD_18_COUNT)
#else
    #define PMBUS_CMD_18_INDEX (0)
#endif

#define PMBUS_CMD_19_COUNT (PMBUS_CMD_18_COUNT + PMBUS_CMD_19_ENABLE)

#if PMBUS_CMD_19_ENABLE
    #define PMBUS_CMD_19_INDEX (PMBUS_CMD_19_COUNT)
#else
    #define PMBUS_CMD_19_INDEX (0)
#endif

#define PMBUS_CMD_1A_COUNT (PMBUS_CMD_19_COUNT + PMBUS_CMD_1A_ENABLE)

#if PMBUS_CMD_1A_ENABLE
    #define PMBUS_CMD_1A_INDEX (PMBUS_CMD_1A_COUNT)
#else
    #define PMBUS_CMD_1A_INDEX (0)
#endif

#define PMBUS_CMD_1B_COUNT (PMBUS_CMD_1A_COUNT + PMBUS_CMD_1B_ENABLE)

#if PMBUS_CMD_1B_ENABLE
    #define PMBUS_CMD_1B_INDEX (PMBUS_CMD_1B_COUNT)
#else
    #define PMBUS_CMD_1B_INDEX (0)
#endif

#define PMBUS_CMD_1C_COUNT (PMBUS_CMD_1B_COUNT + PMBUS_CMD_1C_ENABLE)

#if PMBUS_CMD_1C_ENABLE
    #define PMBUS_CMD_1C_INDEX (PMBUS_CMD_1C_COUNT)
#else
    #define PMBUS_CMD_1C_INDEX (0)
#endif

#define PMBUS_CMD_1D_COUNT (PMBUS_CMD_1C_COUNT + PMBUS_CMD_1D_ENABLE)

#if PMBUS_CMD_1D_ENABLE
    #define PMBUS_CMD_1D_INDEX (PMBUS_CMD_1D_COUNT)
#else
    #define PMBUS_CMD_1D_INDEX (0)
#endif

#define PMBUS_CMD_1E_COUNT (PMBUS_CMD_1D_COUNT + PMBUS_CMD_1E_ENABLE)

#if PMBUS_CMD_1E_ENABLE
    #define PMBUS_CMD_1E_INDEX (PMBUS_CMD_1E_COUNT)
#else
    #define PMBUS_CMD_1E_INDEX (0)
#endif

#define PMBUS_CMD_1F_COUNT (PMBUS_CMD_1E_COUNT + PMBUS_CMD_1F_ENABLE)

#if PMBUS_CMD_1F_ENABLE
    #define PMBUS_CMD_1F_INDEX (PMBUS_CMD_1F_COUNT)
#else
    #define PMBUS_CMD_1F_INDEX (0)
#endif

#define PMBUS_CMD_20_COUNT (PMBUS_CMD_1F_COUNT + PMBUS_CMD_20_ENABLE)

#if PMBUS_CMD_20_ENABLE
    #define PMBUS_CMD_20_INDEX (PMBUS_CMD_20_COUNT)
#else
    #define PMBUS_CMD_20_INDEX (0)
#endif

#define PMBUS_CMD_21_COUNT (PMBUS_CMD_20_COUNT + PMBUS_CMD_21_ENABLE)

#if PMBUS_CMD_21_ENABLE
    #define PMBUS_CMD_21_INDEX (PMBUS_CMD_21_COUNT)
#else
    #define PMBUS_CMD_21_INDEX (0)
#endif

#define PMBUS_CMD_22_COUNT (PMBUS_CMD_21_COUNT + PMBUS_CMD_22_ENABLE)

#if PMBUS_CMD_22_ENABLE
    #define PMBUS_CMD_22_INDEX (PMBUS_CMD_22_COUNT)
#else
    #define PMBUS_CMD_22_INDEX (0)
#endif

#define PMBUS_CMD_23_COUNT (PMBUS_CMD_22_COUNT + PMBUS_CMD_23_ENABLE)

#if PMBUS_CMD_23_ENABLE
    #define PMBUS_CMD_23_INDEX (PMBUS_CMD_23_COUNT)
#else
    #define PMBUS_CMD_23_INDEX (0)
#endif

#define PMBUS_CMD_24_COUNT (PMBUS_CMD_23_COUNT + PMBUS_CMD_24_ENABLE)

#if PMBUS_CMD_24_ENABLE
    #define PMBUS_CMD_24_INDEX (PMBUS_CMD_24_COUNT)
#else
    #define PMBUS_CMD_24_INDEX (0)
#endif

#define PMBUS_CMD_25_COUNT (PMBUS_CMD_24_COUNT + PMBUS_CMD_25_ENABLE)

#if PMBUS_CMD_25_ENABLE
    #define PMBUS_CMD_25_INDEX (PMBUS_CMD_25_COUNT)
#else
    #define PMBUS_CMD_25_INDEX (0)
#endif

#define PMBUS_CMD_26_COUNT (PMBUS_CMD_25_COUNT + PMBUS_CMD_26_ENABLE)

#if PMBUS_CMD_26_ENABLE
    #define PMBUS_CMD_26_INDEX (PMBUS_CMD_26_COUNT)
#else
    #define PMBUS_CMD_26_INDEX (0)
#endif

#define PMBUS_CMD_27_COUNT (PMBUS_CMD_26_COUNT + PMBUS_CMD_27_ENABLE)

#if PMBUS_CMD_27_ENABLE
    #define PMBUS_CMD_27_INDEX (PMBUS_CMD_27_COUNT)
#else
    #define PMBUS_CMD_27_INDEX (0)
#endif

#define PMBUS_CMD_28_COUNT (PMBUS_CMD_27_COUNT + PMBUS_CMD_28_ENABLE)

#if PMBUS_CMD_28_ENABLE
    #define PMBUS_CMD_28_INDEX (PMBUS_CMD_28_COUNT)
#else
    #define PMBUS_CMD_28_INDEX (0)
#endif

#define PMBUS_CMD_29_COUNT (PMBUS_CMD_28_COUNT + PMBUS_CMD_29_ENABLE)

#if PMBUS_CMD_29_ENABLE
    #define PMBUS_CMD_29_INDEX (PMBUS_CMD_29_COUNT)
#else
    #define PMBUS_CMD_29_INDEX (0)
#endif

#define PMBUS_CMD_2A_COUNT (PMBUS_CMD_29_COUNT + PMBUS_CMD_2A_ENABLE)

#if PMBUS_CMD_2A_ENABLE
    #define PMBUS_CMD_2A_INDEX (PMBUS_CMD_2A_COUNT)
#else
    #define PMBUS_CMD_2A_INDEX (0)
#endif

#define PMBUS_CMD_2B_COUNT (PMBUS_CMD_2A_COUNT + PMBUS_CMD_2B_ENABLE)

#if PMBUS_CMD_2B_ENABLE
    #define PMBUS_CMD_2B_INDEX (PMBUS_CMD_2B_COUNT)
#else
    #define PMBUS_CMD_2B_INDEX (0)
#endif

#define PMBUS_CMD_2C_COUNT (PMBUS_CMD_2B_COUNT + PMBUS_CMD_2C_ENABLE)

#if PMBUS_CMD_2C_ENABLE
    #define PMBUS_CMD_2C_INDEX (PMBUS_CMD_2C_COUNT)
#else
    #define PMBUS_CMD_2C_INDEX (0)
#endif

#define PMBUS_CMD_2D_COUNT (PMBUS_CMD_2C_COUNT + PMBUS_CMD_2D_ENABLE)

#if PMBUS_CMD_2D_ENABLE
    #define PMBUS_CMD_2D_INDEX (PMBUS_CMD_2D_COUNT)
#else
    #define PMBUS_CMD_2D_INDEX (0)
#endif

#define PMBUS_CMD_2E_COUNT (PMBUS_CMD_2D_COUNT + PMBUS_CMD_2E_ENABLE)

#if PMBUS_CMD_2E_ENABLE
    #define PMBUS_CMD_2E_INDEX (PMBUS_CMD_2E_COUNT)
#else
    #define PMBUS_CMD_2E_INDEX (0)
#endif

#define PMBUS_CMD_2F_COUNT (PMBUS_CMD_2E_COUNT + PMBUS_CMD_2F_ENABLE)

#if PMBUS_CMD_2F_ENABLE
    #define PMBUS_CMD_2F_INDEX (PMBUS_CMD_2F_COUNT)
#else
    #define PMBUS_CMD_2F_INDEX (0)
#endif

#define PMBUS_CMD_30_COUNT (PMBUS_CMD_2F_COUNT + PMBUS_CMD_30_ENABLE)

#if PMBUS_CMD_30_ENABLE
    #define PMBUS_CMD_30_INDEX (PMBUS_CMD_30_COUNT)
#else
    #define PMBUS_CMD_30_INDEX (0)
#endif

#define PMBUS_CMD_31_COUNT (PMBUS_CMD_30_COUNT + PMBUS_CMD_31_ENABLE)

#if PMBUS_CMD_31_ENABLE
    #define PMBUS_CMD_31_INDEX (PMBUS_CMD_31_COUNT)
#else
    #define PMBUS_CMD_31_INDEX (0)
#endif

#define PMBUS_CMD_32_COUNT (PMBUS_CMD_31_COUNT + PMBUS_CMD_32_ENABLE)

#if PMBUS_CMD_32_ENABLE
    #define PMBUS_CMD_32_INDEX (PMBUS_CMD_32_COUNT)
#else
    #define PMBUS_CMD_32_INDEX (0)
#endif

#define PMBUS_CMD_33_COUNT (PMBUS_CMD_32_COUNT + PMBUS_CMD_33_ENABLE)

#if PMBUS_CMD_33_ENABLE
    #define PMBUS_CMD_33_INDEX (PMBUS_CMD_33_COUNT)
#else
    #define PMBUS_CMD_33_INDEX (0)
#endif

#define PMBUS_CMD_34_COUNT (PMBUS_CMD_33_COUNT + PMBUS_CMD_34_ENABLE)

#if PMBUS_CMD_34_ENABLE
    #define PMBUS_CMD_34_INDEX (PMBUS_CMD_34_COUNT)
#else
    #define PMBUS_CMD_34_INDEX (0)
#endif

#define PMBUS_CMD_35_COUNT (PMBUS_CMD_34_COUNT + PMBUS_CMD_35_ENABLE)

#if PMBUS_CMD_35_ENABLE
    #define PMBUS_CMD_35_INDEX (PMBUS_CMD_35_COUNT)
#else
    #define PMBUS_CMD_35_INDEX (0)
#endif

#define PMBUS_CMD_36_COUNT (PMBUS_CMD_35_COUNT + PMBUS_CMD_36_ENABLE)

#if PMBUS_CMD_36_ENABLE
    #define PMBUS_CMD_36_INDEX (PMBUS_CMD_36_COUNT)
#else
    #define PMBUS_CMD_36_INDEX (0)
#endif

#define PMBUS_CMD_37_COUNT (PMBUS_CMD_36_COUNT + PMBUS_CMD_37_ENABLE)

#if PMBUS_CMD_37_ENABLE
    #define PMBUS_CMD_37_INDEX (PMBUS_CMD_37_COUNT)
#else
    #define PMBUS_CMD_37_INDEX (0)
#endif

#define PMBUS_CMD_38_COUNT (PMBUS_CMD_37_COUNT + PMBUS_CMD_38_ENABLE)

#if PMBUS_CMD_38_ENABLE
    #define PMBUS_CMD_38_INDEX (PMBUS_CMD_38_COUNT)
#else
    #define PMBUS_CMD_38_INDEX (0)
#endif

#define PMBUS_CMD_39_COUNT (PMBUS_CMD_38_COUNT + PMBUS_CMD_39_ENABLE)

#if PMBUS_CMD_39_ENABLE
    #define PMBUS_CMD_39_INDEX (PMBUS_CMD_39_COUNT)
#else
    #define PMBUS_CMD_39_INDEX (0)
#endif

#define PMBUS_CMD_3A_COUNT (PMBUS_CMD_39_COUNT + PMBUS_CMD_3A_ENABLE)

#if PMBUS_CMD_3A_ENABLE
    #define PMBUS_CMD_3A_INDEX (PMBUS_CMD_3A_COUNT)
#else
    #define PMBUS_CMD_3A_INDEX (0)
#endif

#define PMBUS_CMD_3B_COUNT (PMBUS_CMD_3A_COUNT + PMBUS_CMD_3B_ENABLE)

#if PMBUS_CMD_3B_ENABLE
    #define PMBUS_CMD_3B_INDEX (PMBUS_CMD_3B_COUNT)
#else
    #define PMBUS_CMD_3B_INDEX (0)
#endif

#define PMBUS_CMD_3C_COUNT (PMBUS_CMD_3B_COUNT + PMBUS_CMD_3C_ENABLE)

#if PMBUS_CMD_3C_ENABLE
    #define PMBUS_CMD_3C_INDEX (PMBUS_CMD_3C_COUNT)
#else
    #define PMBUS_CMD_3C_INDEX (0)
#endif

#define PMBUS_CMD_3D_COUNT (PMBUS_CMD_3C_COUNT + PMBUS_CMD_3D_ENABLE)

#if PMBUS_CMD_3D_ENABLE
    #define PMBUS_CMD_3D_INDEX (PMBUS_CMD_3D_COUNT)
#else
    #define PMBUS_CMD_3D_INDEX (0)
#endif

#define PMBUS_CMD_3E_COUNT (PMBUS_CMD_3D_COUNT + PMBUS_CMD_3E_ENABLE)

#if PMBUS_CMD_3E_ENABLE
    #define PMBUS_CMD_3E_INDEX (PMBUS_CMD_3E_COUNT)
#else
    #define PMBUS_CMD_3E_INDEX (0)
#endif

#define PMBUS_CMD_3F_COUNT (PMBUS_CMD_3E_COUNT + PMBUS_CMD_3F_ENABLE)

#if PMBUS_CMD_3F_ENABLE
    #define PMBUS_CMD_3F_INDEX (PMBUS_CMD_3F_COUNT)
#else
    #define PMBUS_CMD_3F_INDEX (0)
#endif

#define PMBUS_CMD_40_COUNT (PMBUS_CMD_3F_COUNT + PMBUS_CMD_40_ENABLE)

#if PMBUS_CMD_40_ENABLE
    #define PMBUS_CMD_40_INDEX (PMBUS_CMD_40_COUNT)
#else
    #define PMBUS_CMD_40_INDEX (0)
#endif

#define PMBUS_CMD_41_COUNT (PMBUS_CMD_40_COUNT + PMBUS_CMD_41_ENABLE)

#if PMBUS_CMD_41_ENABLE
    #define PMBUS_CMD_41_INDEX (PMBUS_CMD_41_COUNT)
#else
    #define PMBUS_CMD_41_INDEX (0)
#endif

#define PMBUS_CMD_42_COUNT (PMBUS_CMD_41_COUNT + PMBUS_CMD_42_ENABLE)

#if PMBUS_CMD_42_ENABLE
    #define PMBUS_CMD_42_INDEX (PMBUS_CMD_42_COUNT)
#else
    #define PMBUS_CMD_42_INDEX (0)
#endif

#define PMBUS_CMD_43_COUNT (PMBUS_CMD_42_COUNT + PMBUS_CMD_43_ENABLE)

#if PMBUS_CMD_43_ENABLE
    #define PMBUS_CMD_43_INDEX (PMBUS_CMD_43_COUNT)
#else
    #define PMBUS_CMD_43_INDEX (0)
#endif

#define PMBUS_CMD_44_COUNT (PMBUS_CMD_43_COUNT + PMBUS_CMD_44_ENABLE)

#if PMBUS_CMD_44_ENABLE
    #define PMBUS_CMD_44_INDEX (PMBUS_CMD_44_COUNT)
#else
    #define PMBUS_CMD_44_INDEX (0)
#endif

#define PMBUS_CMD_45_COUNT (PMBUS_CMD_44_COUNT + PMBUS_CMD_45_ENABLE)

#if PMBUS_CMD_45_ENABLE
    #define PMBUS_CMD_45_INDEX (PMBUS_CMD_45_COUNT)
#else
    #define PMBUS_CMD_45_INDEX (0)
#endif

#define PMBUS_CMD_46_COUNT (PMBUS_CMD_45_COUNT + PMBUS_CMD_46_ENABLE)

#if PMBUS_CMD_46_ENABLE
    #define PMBUS_CMD_46_INDEX (PMBUS_CMD_46_COUNT)
#else
    #define PMBUS_CMD_46_INDEX (0)
#endif

#define PMBUS_CMD_47_COUNT (PMBUS_CMD_46_COUNT + PMBUS_CMD_47_ENABLE)

#if PMBUS_CMD_47_ENABLE
    #define PMBUS_CMD_47_INDEX (PMBUS_CMD_47_COUNT)
#else
    #define PMBUS_CMD_47_INDEX (0)
#endif

#define PMBUS_CMD_48_COUNT (PMBUS_CMD_47_COUNT + PMBUS_CMD_48_ENABLE)

#if PMBUS_CMD_48_ENABLE
    #define PMBUS_CMD_48_INDEX (PMBUS_CMD_48_COUNT)
#else
    #define PMBUS_CMD_48_INDEX (0)
#endif

#define PMBUS_CMD_49_COUNT (PMBUS_CMD_48_COUNT + PMBUS_CMD_49_ENABLE)

#if PMBUS_CMD_49_ENABLE
    #define PMBUS_CMD_49_INDEX (PMBUS_CMD_49_COUNT)
#else
    #define PMBUS_CMD_49_INDEX (0)
#endif

#define PMBUS_CMD_4A_COUNT (PMBUS_CMD_49_COUNT + PMBUS_CMD_4A_ENABLE)

#if PMBUS_CMD_4A_ENABLE
    #define PMBUS_CMD_4A_INDEX (PMBUS_CMD_4A_COUNT)
#else
    #define PMBUS_CMD_4A_INDEX (0)
#endif

#define PMBUS_CMD_4B_COUNT (PMBUS_CMD_4A_COUNT + PMBUS_CMD_4B_ENABLE)

#if PMBUS_CMD_4B_ENABLE
    #define PMBUS_CMD_4B_INDEX (PMBUS_CMD_4B_COUNT)
#else
    #define PMBUS_CMD_4B_INDEX (0)
#endif

#define PMBUS_CMD_4C_COUNT (PMBUS_CMD_4B_COUNT + PMBUS_CMD_4C_ENABLE)

#if PMBUS_CMD_4C_ENABLE
    #define PMBUS_CMD_4C_INDEX (PMBUS_CMD_4C_COUNT)
#else
    #define PMBUS_CMD_4C_INDEX (0)
#endif

#define PMBUS_CMD_4D_COUNT (PMBUS_CMD_4C_COUNT + PMBUS_CMD_4D_ENABLE)

#if PMBUS_CMD_4D_ENABLE
    #define PMBUS_CMD_4D_INDEX (PMBUS_CMD_4D_COUNT)
#else
    #define PMBUS_CMD_4D_INDEX (0)
#endif

#define PMBUS_CMD_4E_COUNT (PMBUS_CMD_4D_COUNT + PMBUS_CMD_4E_ENABLE)

#if PMBUS_CMD_4E_ENABLE
    #define PMBUS_CMD_4E_INDEX (PMBUS_CMD_4E_COUNT)
#else
    #define PMBUS_CMD_4E_INDEX (0)
#endif

#define PMBUS_CMD_4F_COUNT (PMBUS_CMD_4E_COUNT + PMBUS_CMD_4F_ENABLE)

#if PMBUS_CMD_4F_ENABLE
    #define PMBUS_CMD_4F_INDEX (PMBUS_CMD_4F_COUNT)
#else
    #define PMBUS_CMD_4F_INDEX (0)
#endif

#define PMBUS_CMD_50_COUNT (PMBUS_CMD_4F_COUNT + PMBUS_CMD_50_ENABLE)

#if PMBUS_CMD_50_ENABLE
    #define PMBUS_CMD_50_INDEX (PMBUS_CMD_50_COUNT)
#else
    #define PMBUS_CMD_50_INDEX (0)
#endif

#define PMBUS_CMD_51_COUNT (PMBUS_CMD_50_COUNT + PMBUS_CMD_51_ENABLE)

#if PMBUS_CMD_51_ENABLE
    #define PMBUS_CMD_51_INDEX (PMBUS_CMD_51_COUNT)
#else
    #define PMBUS_CMD_51_INDEX (0)
#endif

#define PMBUS_CMD_52_COUNT (PMBUS_CMD_51_COUNT + PMBUS_CMD_52_ENABLE)

#if PMBUS_CMD_52_ENABLE
    #define PMBUS_CMD_52_INDEX (PMBUS_CMD_52_COUNT)
#else
    #define PMBUS_CMD_52_INDEX (0)
#endif

#define PMBUS_CMD_53_COUNT (PMBUS_CMD_52_COUNT + PMBUS_CMD_53_ENABLE)

#if PMBUS_CMD_53_ENABLE
    #define PMBUS_CMD_53_INDEX (PMBUS_CMD_53_COUNT)
#else
    #define PMBUS_CMD_53_INDEX (0)
#endif

#define PMBUS_CMD_54_COUNT (PMBUS_CMD_53_COUNT + PMBUS_CMD_54_ENABLE)

#if PMBUS_CMD_54_ENABLE
    #define PMBUS_CMD_54_INDEX (PMBUS_CMD_54_COUNT)
#else
    #define PMBUS_CMD_54_INDEX (0)
#endif

#define PMBUS_CMD_55_COUNT (PMBUS_CMD_54_COUNT + PMBUS_CMD_55_ENABLE)

#if PMBUS_CMD_55_ENABLE
    #define PMBUS_CMD_55_INDEX (PMBUS_CMD_55_COUNT)
#else
    #define PMBUS_CMD_55_INDEX (0)
#endif

#define PMBUS_CMD_56_COUNT (PMBUS_CMD_55_COUNT + PMBUS_CMD_56_ENABLE)

#if PMBUS_CMD_56_ENABLE
    #define PMBUS_CMD_56_INDEX (PMBUS_CMD_56_COUNT)
#else
    #define PMBUS_CMD_56_INDEX (0)
#endif

#define PMBUS_CMD_57_COUNT (PMBUS_CMD_56_COUNT + PMBUS_CMD_57_ENABLE)

#if PMBUS_CMD_57_ENABLE
    #define PMBUS_CMD_57_INDEX (PMBUS_CMD_57_COUNT)
#else
    #define PMBUS_CMD_57_INDEX (0)
#endif

#define PMBUS_CMD_58_COUNT (PMBUS_CMD_57_COUNT + PMBUS_CMD_58_ENABLE)

#if PMBUS_CMD_58_ENABLE
    #define PMBUS_CMD_58_INDEX (PMBUS_CMD_58_COUNT)
#else
    #define PMBUS_CMD_58_INDEX (0)
#endif

#define PMBUS_CMD_59_COUNT (PMBUS_CMD_58_COUNT + PMBUS_CMD_59_ENABLE)

#if PMBUS_CMD_59_ENABLE
    #define PMBUS_CMD_59_INDEX (PMBUS_CMD_59_COUNT)
#else
    #define PMBUS_CMD_59_INDEX (0)
#endif

#define PMBUS_CMD_5A_COUNT (PMBUS_CMD_59_COUNT + PMBUS_CMD_5A_ENABLE)

#if PMBUS_CMD_5A_ENABLE
    #define PMBUS_CMD_5A_INDEX (PMBUS_CMD_5A_COUNT)
#else
    #define PMBUS_CMD_5A_INDEX (0)
#endif

#define PMBUS_CMD_5B_COUNT (PMBUS_CMD_5A_COUNT + PMBUS_CMD_5B_ENABLE)

#if PMBUS_CMD_5B_ENABLE
    #define PMBUS_CMD_5B_INDEX (PMBUS_CMD_5B_COUNT)
#else
    #define PMBUS_CMD_5B_INDEX (0)
#endif

#define PMBUS_CMD_5C_COUNT (PMBUS_CMD_5B_COUNT + PMBUS_CMD_5C_ENABLE)

#if PMBUS_CMD_5C_ENABLE
    #define PMBUS_CMD_5C_INDEX (PMBUS_CMD_5C_COUNT)
#else
    #define PMBUS_CMD_5C_INDEX (0)
#endif

#define PMBUS_CMD_5D_COUNT (PMBUS_CMD_5C_COUNT + PMBUS_CMD_5D_ENABLE)

#if PMBUS_CMD_5D_ENABLE
    #define PMBUS_CMD_5D_INDEX (PMBUS_CMD_5D_COUNT)
#else
    #define PMBUS_CMD_5D_INDEX (0)
#endif

#define PMBUS_CMD_5E_COUNT (PMBUS_CMD_5D_COUNT + PMBUS_CMD_5E_ENABLE)

#if PMBUS_CMD_5E_ENABLE
    #define PMBUS_CMD_5E_INDEX (PMBUS_CMD_5E_COUNT)
#else
    #define PMBUS_CMD_5E_INDEX (0)
#endif

#define PMBUS_CMD_5F_COUNT (PMBUS_CMD_5E_COUNT + PMBUS_CMD_5F_ENABLE)

#if PMBUS_CMD_5F_ENABLE
    #define PMBUS_CMD_5F_INDEX (PMBUS_CMD_5F_COUNT)
#else
    #define PMBUS_CMD_5F_INDEX (0)
#endif

#define PMBUS_CMD_60_COUNT (PMBUS_CMD_5F_COUNT + PMBUS_CMD_60_ENABLE)

#if PMBUS_CMD_60_ENABLE
    #define PMBUS_CMD_60_INDEX (PMBUS_CMD_60_COUNT)
#else
    #define PMBUS_CMD_60_INDEX (0)
#endif

#define PMBUS_CMD_61_COUNT (PMBUS_CMD_60_COUNT + PMBUS_CMD_61_ENABLE)

#if PMBUS_CMD_61_ENABLE
    #define PMBUS_CMD_61_INDEX (PMBUS_CMD_61_COUNT)
#else
    #define PMBUS_CMD_61_INDEX (0)
#endif

#define PMBUS_CMD_62_COUNT (PMBUS_CMD_61_COUNT + PMBUS_CMD_62_ENABLE)

#if PMBUS_CMD_62_ENABLE
    #define PMBUS_CMD_62_INDEX (PMBUS_CMD_62_COUNT)
#else
    #define PMBUS_CMD_62_INDEX (0)
#endif

#define PMBUS_CMD_63_COUNT (PMBUS_CMD_62_COUNT + PMBUS_CMD_63_ENABLE)

#if PMBUS_CMD_63_ENABLE
    #define PMBUS_CMD_63_INDEX (PMBUS_CMD_63_COUNT)
#else
    #define PMBUS_CMD_63_INDEX (0)
#endif

#define PMBUS_CMD_64_COUNT (PMBUS_CMD_63_COUNT + PMBUS_CMD_64_ENABLE)

#if PMBUS_CMD_64_ENABLE
    #define PMBUS_CMD_64_INDEX (PMBUS_CMD_64_COUNT)
#else
    #define PMBUS_CMD_64_INDEX (0)
#endif

#define PMBUS_CMD_65_COUNT (PMBUS_CMD_64_COUNT + PMBUS_CMD_65_ENABLE)

#if PMBUS_CMD_65_ENABLE
    #define PMBUS_CMD_65_INDEX (PMBUS_CMD_65_COUNT)
#else
    #define PMBUS_CMD_65_INDEX (0)
#endif

#define PMBUS_CMD_66_COUNT (PMBUS_CMD_65_COUNT + PMBUS_CMD_66_ENABLE)

#if PMBUS_CMD_66_ENABLE
    #define PMBUS_CMD_66_INDEX (PMBUS_CMD_66_COUNT)
#else
    #define PMBUS_CMD_66_INDEX (0)
#endif

#define PMBUS_CMD_67_COUNT (PMBUS_CMD_66_COUNT + PMBUS_CMD_67_ENABLE)

#if PMBUS_CMD_67_ENABLE
    #define PMBUS_CMD_67_INDEX (PMBUS_CMD_67_COUNT)
#else
    #define PMBUS_CMD_67_INDEX (0)
#endif

#define PMBUS_CMD_68_COUNT (PMBUS_CMD_67_COUNT + PMBUS_CMD_68_ENABLE)

#if PMBUS_CMD_68_ENABLE
    #define PMBUS_CMD_68_INDEX (PMBUS_CMD_68_COUNT)
#else
    #define PMBUS_CMD_68_INDEX (0)
#endif

#define PMBUS_CMD_69_COUNT (PMBUS_CMD_68_COUNT + PMBUS_CMD_69_ENABLE)

#if PMBUS_CMD_69_ENABLE
    #define PMBUS_CMD_69_INDEX (PMBUS_CMD_69_COUNT)
#else
    #define PMBUS_CMD_69_INDEX (0)
#endif

#define PMBUS_CMD_6A_COUNT (PMBUS_CMD_69_COUNT + PMBUS_CMD_6A_ENABLE)

#if PMBUS_CMD_6A_ENABLE
    #define PMBUS_CMD_6A_INDEX (PMBUS_CMD_6A_COUNT)
#else
    #define PMBUS_CMD_6A_INDEX (0)
#endif

#define PMBUS_CMD_6B_COUNT (PMBUS_CMD_6A_COUNT + PMBUS_CMD_6B_ENABLE)

#if PMBUS_CMD_6B_ENABLE
    #define PMBUS_CMD_6B_INDEX (PMBUS_CMD_6B_COUNT)
#else
    #define PMBUS_CMD_6B_INDEX (0)
#endif

#define PMBUS_CMD_6C_COUNT (PMBUS_CMD_6B_COUNT + PMBUS_CMD_6C_ENABLE)

#if PMBUS_CMD_6C_ENABLE
    #define PMBUS_CMD_6C_INDEX (PMBUS_CMD_6C_COUNT)
#else
    #define PMBUS_CMD_6C_INDEX (0)
#endif

#define PMBUS_CMD_6D_COUNT (PMBUS_CMD_6C_COUNT + PMBUS_CMD_6D_ENABLE)

#if PMBUS_CMD_6D_ENABLE
    #define PMBUS_CMD_6D_INDEX (PMBUS_CMD_6D_COUNT)
#else
    #define PMBUS_CMD_6D_INDEX (0)
#endif

#define PMBUS_CMD_6E_COUNT (PMBUS_CMD_6D_COUNT + PMBUS_CMD_6E_ENABLE)

#if PMBUS_CMD_6E_ENABLE
    #define PMBUS_CMD_6E_INDEX (PMBUS_CMD_6E_COUNT)
#else
    #define PMBUS_CMD_6E_INDEX (0)
#endif

#define PMBUS_CMD_6F_COUNT (PMBUS_CMD_6E_COUNT + PMBUS_CMD_6F_ENABLE)

#if PMBUS_CMD_6F_ENABLE
    #define PMBUS_CMD_6F_INDEX (PMBUS_CMD_6F_COUNT)
#else
    #define PMBUS_CMD_6F_INDEX (0)
#endif

#define PMBUS_CMD_70_COUNT (PMBUS_CMD_6F_COUNT + PMBUS_CMD_70_ENABLE)

#if PMBUS_CMD_70_ENABLE
    #define PMBUS_CMD_70_INDEX (PMBUS_CMD_70_COUNT)
#else
    #define PMBUS_CMD_70_INDEX (0)
#endif

#define PMBUS_CMD_71_COUNT (PMBUS_CMD_70_COUNT + PMBUS_CMD_71_ENABLE)

#if PMBUS_CMD_71_ENABLE
    #define PMBUS_CMD_71_INDEX (PMBUS_CMD_71_COUNT)
#else
    #define PMBUS_CMD_71_INDEX (0)
#endif

#define PMBUS_CMD_72_COUNT (PMBUS_CMD_71_COUNT + PMBUS_CMD_72_ENABLE)

#if PMBUS_CMD_72_ENABLE
    #define PMBUS_CMD_72_INDEX (PMBUS_CMD_72_COUNT)
#else
    #define PMBUS_CMD_72_INDEX (0)
#endif

#define PMBUS_CMD_73_COUNT (PMBUS_CMD_72_COUNT + PMBUS_CMD_73_ENABLE)

#if PMBUS_CMD_73_ENABLE
    #define PMBUS_CMD_73_INDEX (PMBUS_CMD_73_COUNT)
#else
    #define PMBUS_CMD_73_INDEX (0)
#endif

#define PMBUS_CMD_74_COUNT (PMBUS_CMD_73_COUNT + PMBUS_CMD_74_ENABLE)

#if PMBUS_CMD_74_ENABLE
    #define PMBUS_CMD_74_INDEX (PMBUS_CMD_74_COUNT)
#else
    #define PMBUS_CMD_74_INDEX (0)
#endif

#define PMBUS_CMD_75_COUNT (PMBUS_CMD_74_COUNT + PMBUS_CMD_75_ENABLE)

#if PMBUS_CMD_75_ENABLE
    #define PMBUS_CMD_75_INDEX (PMBUS_CMD_75_COUNT)
#else
    #define PMBUS_CMD_75_INDEX (0)
#endif

#define PMBUS_CMD_76_COUNT (PMBUS_CMD_75_COUNT + PMBUS_CMD_76_ENABLE)

#if PMBUS_CMD_76_ENABLE
    #define PMBUS_CMD_76_INDEX (PMBUS_CMD_76_COUNT)
#else
    #define PMBUS_CMD_76_INDEX (0)
#endif

#define PMBUS_CMD_77_COUNT (PMBUS_CMD_76_COUNT + PMBUS_CMD_77_ENABLE)

#if PMBUS_CMD_77_ENABLE
    #define PMBUS_CMD_77_INDEX (PMBUS_CMD_77_COUNT)
#else
    #define PMBUS_CMD_77_INDEX (0)
#endif

#define PMBUS_CMD_78_COUNT (PMBUS_CMD_77_COUNT + PMBUS_CMD_78_ENABLE)

#if PMBUS_CMD_78_ENABLE
    #define PMBUS_CMD_78_INDEX (PMBUS_CMD_78_COUNT)
#else
    #define PMBUS_CMD_78_INDEX (0)
#endif

#define PMBUS_CMD_79_COUNT (PMBUS_CMD_78_COUNT + PMBUS_CMD_79_ENABLE)

#if PMBUS_CMD_79_ENABLE
    #define PMBUS_CMD_79_INDEX (PMBUS_CMD_79_COUNT)
#else
    #define PMBUS_CMD_79_INDEX (0)
#endif

#define PMBUS_CMD_7A_COUNT (PMBUS_CMD_79_COUNT + PMBUS_CMD_7A_ENABLE)

#if PMBUS_CMD_7A_ENABLE
    #define PMBUS_CMD_7A_INDEX (PMBUS_CMD_7A_COUNT)
#else
    #define PMBUS_CMD_7A_INDEX (0)
#endif

#define PMBUS_CMD_7B_COUNT (PMBUS_CMD_7A_COUNT + PMBUS_CMD_7B_ENABLE)

#if PMBUS_CMD_7B_ENABLE
    #define PMBUS_CMD_7B_INDEX (PMBUS_CMD_7B_COUNT)
#else
    #define PMBUS_CMD_7B_INDEX (0)
#endif

#define PMBUS_CMD_7C_COUNT (PMBUS_CMD_7B_COUNT + PMBUS_CMD_7C_ENABLE)

#if PMBUS_CMD_7C_ENABLE
    #define PMBUS_CMD_7C_INDEX (PMBUS_CMD_7C_COUNT)
#else
    #define PMBUS_CMD_7C_INDEX (0)
#endif

#define PMBUS_CMD_7D_COUNT (PMBUS_CMD_7C_COUNT + PMBUS_CMD_7D_ENABLE)

#if PMBUS_CMD_7D_ENABLE
    #define PMBUS_CMD_7D_INDEX (PMBUS_CMD_7D_COUNT)
#else
    #define PMBUS_CMD_7D_INDEX (0)
#endif

#define PMBUS_CMD_7E_COUNT (PMBUS_CMD_7D_COUNT + PMBUS_CMD_7E_ENABLE)

#if PMBUS_CMD_7E_ENABLE
    #define PMBUS_CMD_7E_INDEX (PMBUS_CMD_7E_COUNT)
#else
    #define PMBUS_CMD_7E_INDEX (0)
#endif

#define PMBUS_CMD_7F_COUNT (PMBUS_CMD_7E_COUNT + PMBUS_CMD_7F_ENABLE)

#if PMBUS_CMD_7F_ENABLE
    #define PMBUS_CMD_7F_INDEX (PMBUS_CMD_7F_COUNT)
#else
    #define PMBUS_CMD_7F_INDEX (0)
#endif

#define PMBUS_CMD_80_COUNT (PMBUS_CMD_7F_COUNT + PMBUS_CMD_80_ENABLE)

#if PMBUS_CMD_80_ENABLE
    #define PMBUS_CMD_80_INDEX (PMBUS_CMD_80_COUNT)
#else
    #define PMBUS_CMD_80_INDEX (0)
#endif

#define PMBUS_CMD_81_COUNT (PMBUS_CMD_80_COUNT + PMBUS_CMD_81_ENABLE)

#if PMBUS_CMD_81_ENABLE
    #define PMBUS_CMD_81_INDEX (PMBUS_CMD_81_COUNT)
#else
    #define PMBUS_CMD_81_INDEX (0)
#endif

#define PMBUS_CMD_82_COUNT (PMBUS_CMD_81_COUNT + PMBUS_CMD_82_ENABLE)

#if PMBUS_CMD_82_ENABLE
    #define PMBUS_CMD_82_INDEX (PMBUS_CMD_82_COUNT)
#else
    #define PMBUS_CMD_82_INDEX (0)
#endif

#define PMBUS_CMD_83_COUNT (PMBUS_CMD_82_COUNT + PMBUS_CMD_83_ENABLE)

#if PMBUS_CMD_83_ENABLE
    #define PMBUS_CMD_83_INDEX (PMBUS_CMD_83_COUNT)
#else
    #define PMBUS_CMD_83_INDEX (0)
#endif

#define PMBUS_CMD_84_COUNT (PMBUS_CMD_83_COUNT + PMBUS_CMD_84_ENABLE)

#if PMBUS_CMD_84_ENABLE
    #define PMBUS_CMD_84_INDEX (PMBUS_CMD_84_COUNT)
#else
    #define PMBUS_CMD_84_INDEX (0)
#endif

#define PMBUS_CMD_85_COUNT (PMBUS_CMD_84_COUNT + PMBUS_CMD_85_ENABLE)

#if PMBUS_CMD_85_ENABLE
    #define PMBUS_CMD_85_INDEX (PMBUS_CMD_85_COUNT)
#else
    #define PMBUS_CMD_85_INDEX (0)
#endif

#define PMBUS_CMD_86_COUNT (PMBUS_CMD_85_COUNT + PMBUS_CMD_86_ENABLE)

#if PMBUS_CMD_86_ENABLE
    #define PMBUS_CMD_86_INDEX (PMBUS_CMD_86_COUNT)
#else
    #define PMBUS_CMD_86_INDEX (0)
#endif

#define PMBUS_CMD_87_COUNT (PMBUS_CMD_86_COUNT + PMBUS_CMD_87_ENABLE)

#if PMBUS_CMD_87_ENABLE
    #define PMBUS_CMD_87_INDEX (PMBUS_CMD_87_COUNT)
#else
    #define PMBUS_CMD_87_INDEX (0)
#endif

#define PMBUS_CMD_88_COUNT (PMBUS_CMD_87_COUNT + PMBUS_CMD_88_ENABLE)

#if PMBUS_CMD_88_ENABLE
    #define PMBUS_CMD_88_INDEX (PMBUS_CMD_88_COUNT)
#else
    #define PMBUS_CMD_88_INDEX (0)
#endif

#define PMBUS_CMD_89_COUNT (PMBUS_CMD_88_COUNT + PMBUS_CMD_89_ENABLE)

#if PMBUS_CMD_89_ENABLE
    #define PMBUS_CMD_89_INDEX (PMBUS_CMD_89_COUNT)
#else
    #define PMBUS_CMD_89_INDEX (0)
#endif

#define PMBUS_CMD_8A_COUNT (PMBUS_CMD_89_COUNT + PMBUS_CMD_8A_ENABLE)

#if PMBUS_CMD_8A_ENABLE
    #define PMBUS_CMD_8A_INDEX (PMBUS_CMD_8A_COUNT)
#else
    #define PMBUS_CMD_8A_INDEX (0)
#endif

#define PMBUS_CMD_8B_COUNT (PMBUS_CMD_8A_COUNT + PMBUS_CMD_8B_ENABLE)

#if PMBUS_CMD_8B_ENABLE
    #define PMBUS_CMD_8B_INDEX (PMBUS_CMD_8B_COUNT)
#else
    #define PMBUS_CMD_8B_INDEX (0)
#endif

#define PMBUS_CMD_8C_COUNT (PMBUS_CMD_8B_COUNT + PMBUS_CMD_8C_ENABLE)

#if PMBUS_CMD_8C_ENABLE
    #define PMBUS_CMD_8C_INDEX (PMBUS_CMD_8C_COUNT)
#else
    #define PMBUS_CMD_8C_INDEX (0)
#endif

#define PMBUS_CMD_8D_COUNT (PMBUS_CMD_8C_COUNT + PMBUS_CMD_8D_ENABLE)

#if PMBUS_CMD_8D_ENABLE
    #define PMBUS_CMD_8D_INDEX (PMBUS_CMD_8D_COUNT)
#else
    #define PMBUS_CMD_8D_INDEX (0)
#endif

#define PMBUS_CMD_8E_COUNT (PMBUS_CMD_8D_COUNT + PMBUS_CMD_8E_ENABLE)

#if PMBUS_CMD_8E_ENABLE
    #define PMBUS_CMD_8E_INDEX (PMBUS_CMD_8E_COUNT)
#else
    #define PMBUS_CMD_8E_INDEX (0)
#endif

#define PMBUS_CMD_8F_COUNT (PMBUS_CMD_8E_COUNT + PMBUS_CMD_8F_ENABLE)

#if PMBUS_CMD_8F_ENABLE
    #define PMBUS_CMD_8F_INDEX (PMBUS_CMD_8F_COUNT)
#else
    #define PMBUS_CMD_8F_INDEX (0)
#endif

#define PMBUS_CMD_90_COUNT (PMBUS_CMD_8F_COUNT + PMBUS_CMD_90_ENABLE)

#if PMBUS_CMD_90_ENABLE
    #define PMBUS_CMD_90_INDEX (PMBUS_CMD_90_COUNT)
#else
    #define PMBUS_CMD_90_INDEX (0)
#endif

#define PMBUS_CMD_91_COUNT (PMBUS_CMD_90_COUNT + PMBUS_CMD_91_ENABLE)

#if PMBUS_CMD_91_ENABLE
    #define PMBUS_CMD_91_INDEX (PMBUS_CMD_91_COUNT)
#else
    #define PMBUS_CMD_91_INDEX (0)
#endif

#define PMBUS_CMD_92_COUNT (PMBUS_CMD_91_COUNT + PMBUS_CMD_92_ENABLE)

#if PMBUS_CMD_92_ENABLE
    #define PMBUS_CMD_92_INDEX (PMBUS_CMD_92_COUNT)
#else
    #define PMBUS_CMD_92_INDEX (0)
#endif

#define PMBUS_CMD_93_COUNT (PMBUS_CMD_92_COUNT + PMBUS_CMD_93_ENABLE)

#if PMBUS_CMD_93_ENABLE
    #define PMBUS_CMD_93_INDEX (PMBUS_CMD_93_COUNT)
#else
    #define PMBUS_CMD_93_INDEX (0)
#endif

#define PMBUS_CMD_94_COUNT (PMBUS_CMD_93_COUNT + PMBUS_CMD_94_ENABLE)

#if PMBUS_CMD_94_ENABLE
    #define PMBUS_CMD_94_INDEX (PMBUS_CMD_94_COUNT)
#else
    #define PMBUS_CMD_94_INDEX (0)
#endif

#define PMBUS_CMD_95_COUNT (PMBUS_CMD_94_COUNT + PMBUS_CMD_95_ENABLE)

#if PMBUS_CMD_95_ENABLE
    #define PMBUS_CMD_95_INDEX (PMBUS_CMD_95_COUNT)
#else
    #define PMBUS_CMD_95_INDEX (0)
#endif

#define PMBUS_CMD_96_COUNT (PMBUS_CMD_95_COUNT + PMBUS_CMD_96_ENABLE)

#if PMBUS_CMD_96_ENABLE
    #define PMBUS_CMD_96_INDEX (PMBUS_CMD_96_COUNT)
#else
    #define PMBUS_CMD_96_INDEX (0)
#endif

#define PMBUS_CMD_97_COUNT (PMBUS_CMD_96_COUNT + PMBUS_CMD_97_ENABLE)

#if PMBUS_CMD_97_ENABLE
    #define PMBUS_CMD_97_INDEX (PMBUS_CMD_97_COUNT)
#else
    #define PMBUS_CMD_97_INDEX (0)
#endif

#define PMBUS_CMD_98_COUNT (PMBUS_CMD_97_COUNT + PMBUS_CMD_98_ENABLE)

#if PMBUS_CMD_98_ENABLE
    #define PMBUS_CMD_98_INDEX (PMBUS_CMD_98_COUNT)
#else
    #define PMBUS_CMD_98_INDEX (0)
#endif

#define PMBUS_CMD_99_COUNT (PMBUS_CMD_98_COUNT + PMBUS_CMD_99_ENABLE)

#if PMBUS_CMD_99_ENABLE
    #define PMBUS_CMD_99_INDEX (PMBUS_CMD_99_COUNT)
#else
    #define PMBUS_CMD_99_INDEX (0)
#endif

#define PMBUS_CMD_9A_COUNT (PMBUS_CMD_99_COUNT + PMBUS_CMD_9A_ENABLE)

#if PMBUS_CMD_9A_ENABLE
    #define PMBUS_CMD_9A_INDEX (PMBUS_CMD_9A_COUNT)
#else
    #define PMBUS_CMD_9A_INDEX (0)
#endif

#define PMBUS_CMD_9B_COUNT (PMBUS_CMD_9A_COUNT + PMBUS_CMD_9B_ENABLE)

#if PMBUS_CMD_9B_ENABLE
    #define PMBUS_CMD_9B_INDEX (PMBUS_CMD_9B_COUNT)
#else
    #define PMBUS_CMD_9B_INDEX (0)
#endif

#define PMBUS_CMD_9C_COUNT (PMBUS_CMD_9B_COUNT + PMBUS_CMD_9C_ENABLE)

#if PMBUS_CMD_9C_ENABLE
    #define PMBUS_CMD_9C_INDEX (PMBUS_CMD_9C_COUNT)
#else
    #define PMBUS_CMD_9C_INDEX (0)
#endif

#define PMBUS_CMD_9D_COUNT (PMBUS_CMD_9C_COUNT + PMBUS_CMD_9D_ENABLE)

#if PMBUS_CMD_9D_ENABLE
    #define PMBUS_CMD_9D_INDEX (PMBUS_CMD_9D_COUNT)
#else
    #define PMBUS_CMD_9D_INDEX (0)
#endif

#define PMBUS_CMD_9E_COUNT (PMBUS_CMD_9D_COUNT + PMBUS_CMD_9E_ENABLE)

#if PMBUS_CMD_9E_ENABLE
    #define PMBUS_CMD_9E_INDEX (PMBUS_CMD_9E_COUNT)
#else
    #define PMBUS_CMD_9E_INDEX (0)
#endif

#define PMBUS_CMD_9F_COUNT (PMBUS_CMD_9E_COUNT + PMBUS_CMD_9F_ENABLE)

#if PMBUS_CMD_9F_ENABLE
    #define PMBUS_CMD_9F_INDEX (PMBUS_CMD_9F_COUNT)
#else
    #define PMBUS_CMD_9F_INDEX (0)
#endif

#define PMBUS_CMD_A0_COUNT (PMBUS_CMD_9F_COUNT + PMBUS_CMD_A0_ENABLE)

#if PMBUS_CMD_A0_ENABLE
    #define PMBUS_CMD_A0_INDEX (PMBUS_CMD_A0_COUNT)
#else
    #define PMBUS_CMD_A0_INDEX (0)
#endif

#define PMBUS_CMD_A1_COUNT (PMBUS_CMD_A0_COUNT + PMBUS_CMD_A1_ENABLE)

#if PMBUS_CMD_A1_ENABLE
    #define PMBUS_CMD_A1_INDEX (PMBUS_CMD_A1_COUNT)
#else
    #define PMBUS_CMD_A1_INDEX (0)
#endif

#define PMBUS_CMD_A2_COUNT (PMBUS_CMD_A1_COUNT + PMBUS_CMD_A2_ENABLE)

#if PMBUS_CMD_A2_ENABLE
    #define PMBUS_CMD_A2_INDEX (PMBUS_CMD_A2_COUNT)
#else
    #define PMBUS_CMD_A2_INDEX (0)
#endif

#define PMBUS_CMD_A3_COUNT (PMBUS_CMD_A2_COUNT + PMBUS_CMD_A3_ENABLE)

#if PMBUS_CMD_A3_ENABLE
    #define PMBUS_CMD_A3_INDEX (PMBUS_CMD_A3_COUNT)
#else
    #define PMBUS_CMD_A3_INDEX (0)
#endif

#define PMBUS_CMD_A4_COUNT (PMBUS_CMD_A3_COUNT + PMBUS_CMD_A4_ENABLE)

#if PMBUS_CMD_A4_ENABLE
    #define PMBUS_CMD_A4_INDEX (PMBUS_CMD_A4_COUNT)
#else
    #define PMBUS_CMD_A4_INDEX (0)
#endif

#define PMBUS_CMD_A5_COUNT (PMBUS_CMD_A4_COUNT + PMBUS_CMD_A5_ENABLE)

#if PMBUS_CMD_A5_ENABLE
    #define PMBUS_CMD_A5_INDEX (PMBUS_CMD_A5_COUNT)
#else
    #define PMBUS_CMD_A5_INDEX (0)
#endif

#define PMBUS_CMD_A6_COUNT (PMBUS_CMD_A5_COUNT + PMBUS_CMD_A6_ENABLE)

#if PMBUS_CMD_A6_ENABLE
    #define PMBUS_CMD_A6_INDEX (PMBUS_CMD_A6_COUNT)
#else
    #define PMBUS_CMD_A6_INDEX (0)
#endif

#define PMBUS_CMD_A7_COUNT (PMBUS_CMD_A6_COUNT + PMBUS_CMD_A7_ENABLE)

#if PMBUS_CMD_A7_ENABLE
    #define PMBUS_CMD_A7_INDEX (PMBUS_CMD_A7_COUNT)
#else
    #define PMBUS_CMD_A7_INDEX (0)
#endif

#define PMBUS_CMD_A8_COUNT (PMBUS_CMD_A7_COUNT + PMBUS_CMD_A8_ENABLE)

#if PMBUS_CMD_A8_ENABLE
    #define PMBUS_CMD_A8_INDEX (PMBUS_CMD_A8_COUNT)
#else
    #define PMBUS_CMD_A8_INDEX (0)
#endif

#define PMBUS_CMD_A9_COUNT (PMBUS_CMD_A8_COUNT + PMBUS_CMD_A9_ENABLE)

#if PMBUS_CMD_A9_ENABLE
    #define PMBUS_CMD_A9_INDEX (PMBUS_CMD_A9_COUNT)
#else
    #define PMBUS_CMD_A9_INDEX (0)
#endif

#define PMBUS_CMD_AA_COUNT (PMBUS_CMD_A9_COUNT + PMBUS_CMD_AA_ENABLE)

#if PMBUS_CMD_AA_ENABLE
    #define PMBUS_CMD_AA_INDEX (PMBUS_CMD_AA_COUNT)
#else
    #define PMBUS_CMD_AA_INDEX (0)
#endif

#define PMBUS_CMD_AB_COUNT (PMBUS_CMD_AA_COUNT + PMBUS_CMD_AB_ENABLE)

#if PMBUS_CMD_AB_ENABLE
    #define PMBUS_CMD_AB_INDEX (PMBUS_CMD_AB_COUNT)
#else
    #define PMBUS_CMD_AB_INDEX (0)
#endif

#define PMBUS_CMD_AC_COUNT (PMBUS_CMD_AB_COUNT + PMBUS_CMD_AC_ENABLE)

#if PMBUS_CMD_AC_ENABLE
    #define PMBUS_CMD_AC_INDEX (PMBUS_CMD_AC_COUNT)
#else
    #define PMBUS_CMD_AC_INDEX (0)
#endif

#define PMBUS_CMD_AD_COUNT (PMBUS_CMD_AC_COUNT + PMBUS_CMD_AD_ENABLE)

#if PMBUS_CMD_AD_ENABLE
    #define PMBUS_CMD_AD_INDEX (PMBUS_CMD_AD_COUNT)
#else
    #define PMBUS_CMD_AD_INDEX (0)
#endif

#define PMBUS_CMD_AE_COUNT (PMBUS_CMD_AD_COUNT + PMBUS_CMD_AE_ENABLE)

#if PMBUS_CMD_AE_ENABLE
    #define PMBUS_CMD_AE_INDEX (PMBUS_CMD_AE_COUNT)
#else
    #define PMBUS_CMD_AE_INDEX (0)
#endif

#define PMBUS_CMD_AF_COUNT (PMBUS_CMD_AE_COUNT + PMBUS_CMD_AF_ENABLE)

#if PMBUS_CMD_AF_ENABLE
    #define PMBUS_CMD_AF_INDEX (PMBUS_CMD_AF_COUNT)
#else
    #define PMBUS_CMD_AF_INDEX (0)
#endif

#define PMBUS_CMD_B0_COUNT (PMBUS_CMD_AF_COUNT + PMBUS_CMD_B0_ENABLE)

#if PMBUS_CMD_B0_ENABLE
    #define PMBUS_CMD_B0_INDEX (PMBUS_CMD_B0_COUNT)
#else
    #define PMBUS_CMD_B0_INDEX (0)
#endif

#define PMBUS_CMD_B1_COUNT (PMBUS_CMD_B0_COUNT + PMBUS_CMD_B1_ENABLE)

#if PMBUS_CMD_B1_ENABLE
    #define PMBUS_CMD_B1_INDEX (PMBUS_CMD_B1_COUNT)
#else
    #define PMBUS_CMD_B1_INDEX (0)
#endif

#define PMBUS_CMD_B2_COUNT (PMBUS_CMD_B1_COUNT + PMBUS_CMD_B2_ENABLE)

#if PMBUS_CMD_B2_ENABLE
    #define PMBUS_CMD_B2_INDEX (PMBUS_CMD_B2_COUNT)
#else
    #define PMBUS_CMD_B2_INDEX (0)
#endif

#define PMBUS_CMD_B3_COUNT (PMBUS_CMD_B2_COUNT + PMBUS_CMD_B3_ENABLE)

#if PMBUS_CMD_B3_ENABLE
    #define PMBUS_CMD_B3_INDEX (PMBUS_CMD_B3_COUNT)
#else
    #define PMBUS_CMD_B3_INDEX (0)
#endif

#define PMBUS_CMD_B4_COUNT (PMBUS_CMD_B3_COUNT + PMBUS_CMD_B4_ENABLE)

#if PMBUS_CMD_B4_ENABLE
    #define PMBUS_CMD_B4_INDEX (PMBUS_CMD_B4_COUNT)
#else
    #define PMBUS_CMD_B4_INDEX (0)
#endif

#define PMBUS_CMD_B5_COUNT (PMBUS_CMD_B4_COUNT + PMBUS_CMD_B5_ENABLE)

#if PMBUS_CMD_B5_ENABLE
    #define PMBUS_CMD_B5_INDEX (PMBUS_CMD_B5_COUNT)
#else
    #define PMBUS_CMD_B5_INDEX (0)
#endif

#define PMBUS_CMD_B6_COUNT (PMBUS_CMD_B5_COUNT + PMBUS_CMD_B6_ENABLE)

#if PMBUS_CMD_B6_ENABLE
    #define PMBUS_CMD_B6_INDEX (PMBUS_CMD_B6_COUNT)
#else
    #define PMBUS_CMD_B6_INDEX (0)
#endif

#define PMBUS_CMD_B7_COUNT (PMBUS_CMD_B6_COUNT + PMBUS_CMD_B7_ENABLE)

#if PMBUS_CMD_B7_ENABLE
    #define PMBUS_CMD_B7_INDEX (PMBUS_CMD_B7_COUNT)
#else
    #define PMBUS_CMD_B7_INDEX (0)
#endif

#define PMBUS_CMD_B8_COUNT (PMBUS_CMD_B7_COUNT + PMBUS_CMD_B8_ENABLE)

#if PMBUS_CMD_B8_ENABLE
    #define PMBUS_CMD_B8_INDEX (PMBUS_CMD_B8_COUNT)
#else
    #define PMBUS_CMD_B8_INDEX (0)
#endif

#define PMBUS_CMD_B9_COUNT (PMBUS_CMD_B8_COUNT + PMBUS_CMD_B9_ENABLE)

#if PMBUS_CMD_B9_ENABLE
    #define PMBUS_CMD_B9_INDEX (PMBUS_CMD_B9_COUNT)
#else
    #define PMBUS_CMD_B9_INDEX (0)
#endif

#define PMBUS_CMD_BA_COUNT (PMBUS_CMD_B9_COUNT + PMBUS_CMD_BA_ENABLE)

#if PMBUS_CMD_BA_ENABLE
    #define PMBUS_CMD_BA_INDEX (PMBUS_CMD_BA_COUNT)
#else
    #define PMBUS_CMD_BA_INDEX (0)
#endif

#define PMBUS_CMD_BB_COUNT (PMBUS_CMD_BA_COUNT + PMBUS_CMD_BB_ENABLE)

#if PMBUS_CMD_BB_ENABLE
    #define PMBUS_CMD_BB_INDEX (PMBUS_CMD_BB_COUNT)
#else
    #define PMBUS_CMD_BB_INDEX (0)
#endif

#define PMBUS_CMD_BC_COUNT (PMBUS_CMD_BB_COUNT + PMBUS_CMD_BC_ENABLE)

#if PMBUS_CMD_BC_ENABLE
    #define PMBUS_CMD_BC_INDEX (PMBUS_CMD_BC_COUNT)
#else
    #define PMBUS_CMD_BC_INDEX (0)
#endif

#define PMBUS_CMD_BD_COUNT (PMBUS_CMD_BC_COUNT + PMBUS_CMD_BD_ENABLE)

#if PMBUS_CMD_BD_ENABLE
    #define PMBUS_CMD_BD_INDEX (PMBUS_CMD_BD_COUNT)
#else
    #define PMBUS_CMD_BD_INDEX (0)
#endif

#define PMBUS_CMD_BE_COUNT (PMBUS_CMD_BD_COUNT + PMBUS_CMD_BE_ENABLE)

#if PMBUS_CMD_BE_ENABLE
    #define PMBUS_CMD_BE_INDEX (PMBUS_CMD_BE_COUNT)
#else
    #define PMBUS_CMD_BE_INDEX (0)
#endif

#define PMBUS_CMD_BF_COUNT (PMBUS_CMD_BE_COUNT + PMBUS_CMD_BF_ENABLE)

#if PMBUS_CMD_BF_ENABLE
    #define PMBUS_CMD_BF_INDEX (PMBUS_CMD_BF_COUNT)
#else
    #define PMBUS_CMD_BF_INDEX (0)
#endif

#define PMBUS_CMD_C0_COUNT (PMBUS_CMD_BF_COUNT + PMBUS_CMD_C0_ENABLE)

#if PMBUS_CMD_C0_ENABLE
    #define PMBUS_CMD_C0_INDEX (PMBUS_CMD_C0_COUNT)
#else
    #define PMBUS_CMD_C0_INDEX (0)
#endif

#define PMBUS_CMD_C1_COUNT (PMBUS_CMD_C0_COUNT + PMBUS_CMD_C1_ENABLE)

#if PMBUS_CMD_C1_ENABLE
    #define PMBUS_CMD_C1_INDEX (PMBUS_CMD_C1_COUNT)
#else
    #define PMBUS_CMD_C1_INDEX (0)
#endif

#define PMBUS_CMD_C2_COUNT (PMBUS_CMD_C1_COUNT + PMBUS_CMD_C2_ENABLE)

#if PMBUS_CMD_C2_ENABLE
    #define PMBUS_CMD_C2_INDEX (PMBUS_CMD_C2_COUNT)
#else
    #define PMBUS_CMD_C2_INDEX (0)
#endif

#define PMBUS_CMD_C3_COUNT (PMBUS_CMD_C2_COUNT + PMBUS_CMD_C3_ENABLE)

#if PMBUS_CMD_C3_ENABLE
    #define PMBUS_CMD_C3_INDEX (PMBUS_CMD_C3_COUNT)
#else
    #define PMBUS_CMD_C3_INDEX (0)
#endif

#define PMBUS_CMD_C4_COUNT (PMBUS_CMD_C3_COUNT + PMBUS_CMD_C4_ENABLE)

#if PMBUS_CMD_C4_ENABLE
    #define PMBUS_CMD_C4_INDEX (PMBUS_CMD_C4_COUNT)
#else
    #define PMBUS_CMD_C4_INDEX (0)
#endif

#define PMBUS_CMD_C5_COUNT (PMBUS_CMD_C4_COUNT + PMBUS_CMD_C5_ENABLE)

#if PMBUS_CMD_C5_ENABLE
    #define PMBUS_CMD_C5_INDEX (PMBUS_CMD_C5_COUNT)
#else
    #define PMBUS_CMD_C5_INDEX (0)
#endif

#define PMBUS_CMD_C6_COUNT (PMBUS_CMD_C5_COUNT + PMBUS_CMD_C6_ENABLE)

#if PMBUS_CMD_C6_ENABLE
    #define PMBUS_CMD_C6_INDEX (PMBUS_CMD_C6_COUNT)
#else
    #define PMBUS_CMD_C6_INDEX (0)
#endif

#define PMBUS_CMD_C7_COUNT (PMBUS_CMD_C6_COUNT + PMBUS_CMD_C7_ENABLE)

#if PMBUS_CMD_C7_ENABLE
    #define PMBUS_CMD_C7_INDEX (PMBUS_CMD_C7_COUNT)
#else
    #define PMBUS_CMD_C7_INDEX (0)
#endif

#define PMBUS_CMD_C8_COUNT (PMBUS_CMD_C7_COUNT + PMBUS_CMD_C8_ENABLE)

#if PMBUS_CMD_C8_ENABLE
    #define PMBUS_CMD_C8_INDEX (PMBUS_CMD_C8_COUNT)
#else
    #define PMBUS_CMD_C8_INDEX (0)
#endif

#define PMBUS_CMD_C9_COUNT (PMBUS_CMD_C8_COUNT + PMBUS_CMD_C9_ENABLE)

#if PMBUS_CMD_C9_ENABLE
    #define PMBUS_CMD_C9_INDEX (PMBUS_CMD_C9_COUNT)
#else
    #define PMBUS_CMD_C9_INDEX (0)
#endif

#define PMBUS_CMD_CA_COUNT (PMBUS_CMD_C9_COUNT + PMBUS_CMD_CA_ENABLE)

#if PMBUS_CMD_CA_ENABLE
    #define PMBUS_CMD_CA_INDEX (PMBUS_CMD_CA_COUNT)
#else
    #define PMBUS_CMD_CA_INDEX (0)
#endif

#define PMBUS_CMD_CB_COUNT (PMBUS_CMD_CA_COUNT + PMBUS_CMD_CB_ENABLE)

#if PMBUS_CMD_CB_ENABLE
    #define PMBUS_CMD_CB_INDEX (PMBUS_CMD_CB_COUNT)
#else
    #define PMBUS_CMD_CB_INDEX (0)
#endif

#define PMBUS_CMD_CC_COUNT (PMBUS_CMD_CB_COUNT + PMBUS_CMD_CC_ENABLE)

#if PMBUS_CMD_CC_ENABLE
    #define PMBUS_CMD_CC_INDEX (PMBUS_CMD_CC_COUNT)
#else
    #define PMBUS_CMD_CC_INDEX (0)
#endif

#define PMBUS_CMD_CD_COUNT (PMBUS_CMD_CC_COUNT + PMBUS_CMD_CD_ENABLE)

#if PMBUS_CMD_CD_ENABLE
    #define PMBUS_CMD_CD_INDEX (PMBUS_CMD_CD_COUNT)
#else
    #define PMBUS_CMD_CD_INDEX (0)
#endif

#define PMBUS_CMD_CE_COUNT (PMBUS_CMD_CD_COUNT + PMBUS_CMD_CE_ENABLE)

#if PMBUS_CMD_CE_ENABLE
    #define PMBUS_CMD_CE_INDEX (PMBUS_CMD_CE_COUNT)
#else
    #define PMBUS_CMD_CE_INDEX (0)
#endif

#define PMBUS_CMD_CF_COUNT (PMBUS_CMD_CE_COUNT + PMBUS_CMD_CF_ENABLE)

#if PMBUS_CMD_CF_ENABLE
    #define PMBUS_CMD_CF_INDEX (PMBUS_CMD_CF_COUNT)
#else
    #define PMBUS_CMD_CF_INDEX (0)
#endif

#define PMBUS_CMD_D0_COUNT (PMBUS_CMD_CF_COUNT + PMBUS_CMD_D0_ENABLE)

#if PMBUS_CMD_D0_ENABLE
    #define PMBUS_CMD_D0_INDEX (PMBUS_CMD_D0_COUNT)
#else
    #define PMBUS_CMD_D0_INDEX (0)
#endif

#define PMBUS_CMD_D1_COUNT (PMBUS_CMD_D0_COUNT + PMBUS_CMD_D1_ENABLE)

#if PMBUS_CMD_D1_ENABLE
    #define PMBUS_CMD_D1_INDEX (PMBUS_CMD_D1_COUNT)
#else
    #define PMBUS_CMD_D1_INDEX (0)
#endif

#define PMBUS_CMD_D2_COUNT (PMBUS_CMD_D1_COUNT + PMBUS_CMD_D2_ENABLE)

#if PMBUS_CMD_D2_ENABLE
    #define PMBUS_CMD_D2_INDEX (PMBUS_CMD_D2_COUNT)
#else
    #define PMBUS_CMD_D2_INDEX (0)
#endif

#define PMBUS_CMD_D3_COUNT (PMBUS_CMD_D2_COUNT + PMBUS_CMD_D3_ENABLE)

#if PMBUS_CMD_D3_ENABLE
    #define PMBUS_CMD_D3_INDEX (PMBUS_CMD_D3_COUNT)
#else
    #define PMBUS_CMD_D3_INDEX (0)
#endif

#define PMBUS_CMD_D4_COUNT (PMBUS_CMD_D3_COUNT + PMBUS_CMD_D4_ENABLE)

#if PMBUS_CMD_D4_ENABLE
    #define PMBUS_CMD_D4_INDEX (PMBUS_CMD_D4_COUNT)
#else
    #define PMBUS_CMD_D4_INDEX (0)
#endif

#define PMBUS_CMD_D5_COUNT (PMBUS_CMD_D4_COUNT + PMBUS_CMD_D5_ENABLE)

#if PMBUS_CMD_D5_ENABLE
    #define PMBUS_CMD_D5_INDEX (PMBUS_CMD_D5_COUNT)
#else
    #define PMBUS_CMD_D5_INDEX (0)
#endif

#define PMBUS_CMD_D6_COUNT (PMBUS_CMD_D5_COUNT + PMBUS_CMD_D6_ENABLE)

#if PMBUS_CMD_D6_ENABLE
    #define PMBUS_CMD_D6_INDEX (PMBUS_CMD_D6_COUNT)
#else
    #define PMBUS_CMD_D6_INDEX (0)
#endif

#define PMBUS_CMD_D7_COUNT (PMBUS_CMD_D6_COUNT + PMBUS_CMD_D7_ENABLE)

#if PMBUS_CMD_D7_ENABLE
    #define PMBUS_CMD_D7_INDEX (PMBUS_CMD_D7_COUNT)
#else
    #define PMBUS_CMD_D7_INDEX (0)
#endif

#define PMBUS_CMD_D8_COUNT (PMBUS_CMD_D7_COUNT + PMBUS_CMD_D8_ENABLE)

#if PMBUS_CMD_D8_ENABLE
    #define PMBUS_CMD_D8_INDEX (PMBUS_CMD_D8_COUNT)
#else
    #define PMBUS_CMD_D8_INDEX (0)
#endif

#define PMBUS_CMD_D9_COUNT (PMBUS_CMD_D8_COUNT + PMBUS_CMD_D9_ENABLE)

#if PMBUS_CMD_D9_ENABLE
    #define PMBUS_CMD_D9_INDEX (PMBUS_CMD_D9_COUNT)
#else
    #define PMBUS_CMD_D9_INDEX (0)
#endif

#define PMBUS_CMD_DA_COUNT (PMBUS_CMD_D9_COUNT + PMBUS_CMD_DA_ENABLE)

#if PMBUS_CMD_DA_ENABLE
    #define PMBUS_CMD_DA_INDEX (PMBUS_CMD_DA_COUNT)
#else
    #define PMBUS_CMD_DA_INDEX (0)
#endif

#define PMBUS_CMD_DB_COUNT (PMBUS_CMD_DA_COUNT + PMBUS_CMD_DB_ENABLE)

#if PMBUS_CMD_DB_ENABLE
    #define PMBUS_CMD_DB_INDEX (PMBUS_CMD_DB_COUNT)
#else
    #define PMBUS_CMD_DB_INDEX (0)
#endif

#define PMBUS_CMD_DC_COUNT (PMBUS_CMD_DB_COUNT + PMBUS_CMD_DC_ENABLE)

#if PMBUS_CMD_DC_ENABLE
    #define PMBUS_CMD_DC_INDEX (PMBUS_CMD_DC_COUNT)
#else
    #define PMBUS_CMD_DC_INDEX (0)
#endif

#define PMBUS_CMD_DD_COUNT (PMBUS_CMD_DC_COUNT + PMBUS_CMD_DD_ENABLE)

#if PMBUS_CMD_DD_ENABLE
    #define PMBUS_CMD_DD_INDEX (PMBUS_CMD_DD_COUNT)
#else
    #define PMBUS_CMD_DD_INDEX (0)
#endif

#define PMBUS_CMD_DE_COUNT (PMBUS_CMD_DD_COUNT + PMBUS_CMD_DE_ENABLE)

#if PMBUS_CMD_DE_ENABLE
    #define PMBUS_CMD_DE_INDEX (PMBUS_CMD_DE_COUNT)
#else
    #define PMBUS_CMD_DE_INDEX (0)
#endif

#define PMBUS_CMD_DF_COUNT (PMBUS_CMD_DE_COUNT + PMBUS_CMD_DF_ENABLE)

#if PMBUS_CMD_DF_ENABLE
    #define PMBUS_CMD_DF_INDEX (PMBUS_CMD_DF_COUNT)
#else
    #define PMBUS_CMD_DF_INDEX (0)
#endif

#define PMBUS_CMD_E0_COUNT (PMBUS_CMD_DF_COUNT + PMBUS_CMD_E0_ENABLE)

#if PMBUS_CMD_E0_ENABLE
    #define PMBUS_CMD_E0_INDEX (PMBUS_CMD_E0_COUNT)
#else
    #define PMBUS_CMD_E0_INDEX (0)
#endif

#define PMBUS_CMD_E1_COUNT (PMBUS_CMD_E0_COUNT + PMBUS_CMD_E1_ENABLE)

#if PMBUS_CMD_E1_ENABLE
    #define PMBUS_CMD_E1_INDEX (PMBUS_CMD_E1_COUNT)
#else
    #define PMBUS_CMD_E1_INDEX (0)
#endif

#define PMBUS_CMD_E2_COUNT (PMBUS_CMD_E1_COUNT + PMBUS_CMD_E2_ENABLE)

#if PMBUS_CMD_E2_ENABLE
    #define PMBUS_CMD_E2_INDEX (PMBUS_CMD_E2_COUNT)
#else
    #define PMBUS_CMD_E2_INDEX (0)
#endif

#define PMBUS_CMD_E3_COUNT (PMBUS_CMD_E2_COUNT + PMBUS_CMD_E3_ENABLE)

#if PMBUS_CMD_E3_ENABLE
    #define PMBUS_CMD_E3_INDEX (PMBUS_CMD_E3_COUNT)
#else
    #define PMBUS_CMD_E3_INDEX (0)
#endif

#define PMBUS_CMD_E4_COUNT (PMBUS_CMD_E3_COUNT + PMBUS_CMD_E4_ENABLE)

#if PMBUS_CMD_E4_ENABLE
    #define PMBUS_CMD_E4_INDEX (PMBUS_CMD_E4_COUNT)
#else
    #define PMBUS_CMD_E4_INDEX (0)
#endif

#define PMBUS_CMD_E5_COUNT (PMBUS_CMD_E4_COUNT + PMBUS_CMD_E5_ENABLE)

#if PMBUS_CMD_E5_ENABLE
    #define PMBUS_CMD_E5_INDEX (PMBUS_CMD_E5_COUNT)
#else
    #define PMBUS_CMD_E5_INDEX (0)
#endif

#define PMBUS_CMD_E6_COUNT (PMBUS_CMD_E5_COUNT + PMBUS_CMD_E6_ENABLE)

#if PMBUS_CMD_E6_ENABLE
    #define PMBUS_CMD_E6_INDEX (PMBUS_CMD_E6_COUNT)
#else
    #define PMBUS_CMD_E6_INDEX (0)
#endif

#define PMBUS_CMD_E7_COUNT (PMBUS_CMD_E6_COUNT + PMBUS_CMD_E7_ENABLE)

#if PMBUS_CMD_E7_ENABLE
    #define PMBUS_CMD_E7_INDEX (PMBUS_CMD_E7_COUNT)
#else
    #define PMBUS_CMD_E7_INDEX (0)
#endif

#define PMBUS_CMD_E8_COUNT (PMBUS_CMD_E7_COUNT + PMBUS_CMD_E8_ENABLE)

#if PMBUS_CMD_E8_ENABLE
    #define PMBUS_CMD_E8_INDEX (PMBUS_CMD_E8_COUNT)
#else
    #define PMBUS_CMD_E8_INDEX (0)
#endif

#define PMBUS_CMD_E9_COUNT (PMBUS_CMD_E8_COUNT + PMBUS_CMD_E9_ENABLE)

#if PMBUS_CMD_E9_ENABLE
    #define PMBUS_CMD_E9_INDEX (PMBUS_CMD_E9_COUNT)
#else
    #define PMBUS_CMD_E9_INDEX (0)
#endif

#define PMBUS_CMD_EA_COUNT (PMBUS_CMD_E9_COUNT + PMBUS_CMD_EA_ENABLE)

#if PMBUS_CMD_EA_ENABLE
    #define PMBUS_CMD_EA_INDEX (PMBUS_CMD_EA_COUNT)
#else
    #define PMBUS_CMD_EA_INDEX (0)
#endif

#define PMBUS_CMD_EB_COUNT (PMBUS_CMD_EA_COUNT + PMBUS_CMD_EB_ENABLE)

#if PMBUS_CMD_EB_ENABLE
    #define PMBUS_CMD_EB_INDEX (PMBUS_CMD_EB_COUNT)
#else
    #define PMBUS_CMD_EB_INDEX (0)
#endif

#define PMBUS_CMD_EC_COUNT (PMBUS_CMD_EB_COUNT + PMBUS_CMD_EC_ENABLE)

#if PMBUS_CMD_EC_ENABLE
    #define PMBUS_CMD_EC_INDEX (PMBUS_CMD_EC_COUNT)
#else
    #define PMBUS_CMD_EC_INDEX (0)
#endif

#define PMBUS_CMD_ED_COUNT (PMBUS_CMD_EC_COUNT + PMBUS_CMD_ED_ENABLE)

#if PMBUS_CMD_ED_ENABLE
    #define PMBUS_CMD_ED_INDEX (PMBUS_CMD_ED_COUNT)
#else
    #define PMBUS_CMD_ED_INDEX (0)
#endif

#define PMBUS_CMD_EE_COUNT (PMBUS_CMD_ED_COUNT + PMBUS_CMD_EE_ENABLE)

#if PMBUS_CMD_EE_ENABLE
    #define PMBUS_CMD_EE_INDEX (PMBUS_CMD_EE_COUNT)
#else
    #define PMBUS_CMD_EE_INDEX (0)
#endif

#define PMBUS_CMD_EF_COUNT (PMBUS_CMD_EE_COUNT + PMBUS_CMD_EF_ENABLE)

#if PMBUS_CMD_EF_ENABLE
    #define PMBUS_CMD_EF_INDEX (PMBUS_CMD_EF_COUNT)
#else
    #define PMBUS_CMD_EF_INDEX (0)
#endif

#define PMBUS_CMD_F0_COUNT (PMBUS_CMD_EF_COUNT + PMBUS_CMD_F0_ENABLE)

#if PMBUS_CMD_F0_ENABLE
    #define PMBUS_CMD_F0_INDEX (PMBUS_CMD_F0_COUNT)
#else
    #define PMBUS_CMD_F0_INDEX (0)
#endif

#define PMBUS_CMD_F1_COUNT (PMBUS_CMD_F0_COUNT + PMBUS_CMD_F1_ENABLE)

#if PMBUS_CMD_F1_ENABLE
    #define PMBUS_CMD_F1_INDEX (PMBUS_CMD_F1_COUNT)
#else
    #define PMBUS_CMD_F1_INDEX (0)
#endif

#define PMBUS_CMD_F2_COUNT (PMBUS_CMD_F1_COUNT + PMBUS_CMD_F2_ENABLE)

#if PMBUS_CMD_F2_ENABLE
    #define PMBUS_CMD_F2_INDEX (PMBUS_CMD_F2_COUNT)
#else
    #define PMBUS_CMD_F2_INDEX (0)
#endif

#define PMBUS_CMD_F3_COUNT (PMBUS_CMD_F2_COUNT + PMBUS_CMD_F3_ENABLE)

#if PMBUS_CMD_F3_ENABLE
    #define PMBUS_CMD_F3_INDEX (PMBUS_CMD_F3_COUNT)
#else
    #define PMBUS_CMD_F3_INDEX (0)
#endif

#define PMBUS_CMD_F4_COUNT (PMBUS_CMD_F3_COUNT + PMBUS_CMD_F4_ENABLE)

#if PMBUS_CMD_F4_ENABLE
    #define PMBUS_CMD_F4_INDEX (PMBUS_CMD_F4_COUNT)
#else
    #define PMBUS_CMD_F4_INDEX (0)
#endif

#define PMBUS_CMD_F5_COUNT (PMBUS_CMD_F4_COUNT + PMBUS_CMD_F5_ENABLE)

#if PMBUS_CMD_F5_ENABLE
    #define PMBUS_CMD_F5_INDEX (PMBUS_CMD_F5_COUNT)
#else
    #define PMBUS_CMD_F5_INDEX (0)
#endif

#define PMBUS_CMD_F6_COUNT (PMBUS_CMD_F5_COUNT + PMBUS_CMD_F6_ENABLE)

#if PMBUS_CMD_F6_ENABLE
    #define PMBUS_CMD_F6_INDEX (PMBUS_CMD_F6_COUNT)
#else
    #define PMBUS_CMD_F6_INDEX (0)
#endif

#define PMBUS_CMD_F7_COUNT (PMBUS_CMD_F6_COUNT + PMBUS_CMD_F7_ENABLE)

#if PMBUS_CMD_F7_ENABLE
    #define PMBUS_CMD_F7_INDEX (PMBUS_CMD_F7_COUNT)
#else
    #define PMBUS_CMD_F7_INDEX (0)
#endif

#define PMBUS_CMD_F8_COUNT (PMBUS_CMD_F7_COUNT + PMBUS_CMD_F8_ENABLE)

#if PMBUS_CMD_F8_ENABLE
    #define PMBUS_CMD_F8_INDEX (PMBUS_CMD_F8_COUNT)
#else
    #define PMBUS_CMD_F8_INDEX (0)
#endif

#define PMBUS_CMD_F9_COUNT (PMBUS_CMD_F8_COUNT + PMBUS_CMD_F9_ENABLE)

#if PMBUS_CMD_F9_ENABLE
    #define PMBUS_CMD_F9_INDEX (PMBUS_CMD_F9_COUNT)
#else
    #define PMBUS_CMD_F9_INDEX (0)
#endif

#define PMBUS_CMD_FA_COUNT (PMBUS_CMD_F9_COUNT + PMBUS_CMD_FA_ENABLE)

#if PMBUS_CMD_FA_ENABLE
    #define PMBUS_CMD_FA_INDEX (PMBUS_CMD_FA_COUNT)
#else
    #define PMBUS_CMD_FA_INDEX (0)
#endif

#define PMBUS_CMD_FB_COUNT (PMBUS_CMD_FA_COUNT + PMBUS_CMD_FB_ENABLE)

#if PMBUS_CMD_FB_ENABLE
    #define PMBUS_CMD_FB_INDEX (PMBUS_CMD_FB_COUNT)
#else
    #define PMBUS_CMD_FB_INDEX (0)
#endif

#define PMBUS_CMD_FC_COUNT (PMBUS_CMD_FB_COUNT + PMBUS_CMD_FC_ENABLE)

#if PMBUS_CMD_FC_ENABLE
    #define PMBUS_CMD_FC_INDEX (PMBUS_CMD_FC_COUNT)
#else
    #define PMBUS_CMD_FC_INDEX (0)
#endif

#define PMBUS_CMD_FD_COUNT (PMBUS_CMD_FC_COUNT + PMBUS_CMD_FD_ENABLE)

#if PMBUS_CMD_FD_ENABLE
    #define PMBUS_CMD_FD_INDEX (PMBUS_CMD_FD_COUNT)
#else
    #define PMBUS_CMD_FD_INDEX (0)
#endif

#define PMBUS_CMD_FE_COUNT (PMBUS_CMD_FD_COUNT + PMBUS_CMD_FE_ENABLE)

#if PMBUS_CMD_FE_ENABLE
    #define PMBUS_CMD_FE_INDEX (PMBUS_CMD_FE_COUNT)
#else
    #define PMBUS_CMD_FE_INDEX (0)
#endif

#define PMBUS_CMD_FF_COUNT (PMBUS_CMD_FE_COUNT + PMBUS_CMD_FF_ENABLE)

#if PMBUS_CMD_FF_ENABLE
    #define PMBUS_CMD_FF_INDEX (PMBUS_CMD_FF_COUNT)
#else
    #define PMBUS_CMD_FF_INDEX (0)
#endif



volatile const Uint8 pmbus_index_array[256] =
{
        PMBUS_CMD_00_INDEX,
        PMBUS_CMD_01_INDEX,
        PMBUS_CMD_02_INDEX,
        PMBUS_CMD_03_INDEX,
        PMBUS_CMD_04_INDEX,
        PMBUS_CMD_05_INDEX,
        PMBUS_CMD_06_INDEX,
        PMBUS_CMD_07_INDEX,
        PMBUS_CMD_08_INDEX,
        PMBUS_CMD_09_INDEX,
        PMBUS_CMD_0A_INDEX,
        PMBUS_CMD_0B_INDEX,
        PMBUS_CMD_0C_INDEX,
        PMBUS_CMD_0D_INDEX,
        PMBUS_CMD_0E_INDEX,
        PMBUS_CMD_0F_INDEX,
        PMBUS_CMD_10_INDEX,
        PMBUS_CMD_11_INDEX,
        PMBUS_CMD_12_INDEX,
        PMBUS_CMD_13_INDEX,
        PMBUS_CMD_14_INDEX,
        PMBUS_CMD_15_INDEX,
        PMBUS_CMD_16_INDEX,
        PMBUS_CMD_17_INDEX,
        PMBUS_CMD_18_INDEX,
        PMBUS_CMD_19_INDEX,
        PMBUS_CMD_1A_INDEX,
        PMBUS_CMD_1B_INDEX,
        PMBUS_CMD_1C_INDEX,
        PMBUS_CMD_1D_INDEX,
        PMBUS_CMD_1E_INDEX,
        PMBUS_CMD_1F_INDEX,
        PMBUS_CMD_20_INDEX,
        PMBUS_CMD_21_INDEX,
        PMBUS_CMD_22_INDEX,
        PMBUS_CMD_23_INDEX,
        PMBUS_CMD_24_INDEX,
        PMBUS_CMD_25_INDEX,
        PMBUS_CMD_26_INDEX,
        PMBUS_CMD_27_INDEX,
        PMBUS_CMD_28_INDEX,
        PMBUS_CMD_29_INDEX,
        PMBUS_CMD_2A_INDEX,
        PMBUS_CMD_2B_INDEX,
        PMBUS_CMD_2C_INDEX,
        PMBUS_CMD_2D_INDEX,
        PMBUS_CMD_2E_INDEX,
        PMBUS_CMD_2F_INDEX,
        PMBUS_CMD_30_INDEX,
        PMBUS_CMD_31_INDEX,
        PMBUS_CMD_32_INDEX,
        PMBUS_CMD_33_INDEX,
        PMBUS_CMD_34_INDEX,
        PMBUS_CMD_35_INDEX,
        PMBUS_CMD_36_INDEX,
        PMBUS_CMD_37_INDEX,
        PMBUS_CMD_38_INDEX,
        PMBUS_CMD_39_INDEX,
        PMBUS_CMD_3A_INDEX,
        PMBUS_CMD_3B_INDEX,
        PMBUS_CMD_3C_INDEX,
        PMBUS_CMD_3D_INDEX,
        PMBUS_CMD_3E_INDEX,
        PMBUS_CMD_3F_INDEX,
        PMBUS_CMD_40_INDEX,
        PMBUS_CMD_41_INDEX,
        PMBUS_CMD_42_INDEX,
        PMBUS_CMD_43_INDEX,
        PMBUS_CMD_44_INDEX,
        PMBUS_CMD_45_INDEX,
        PMBUS_CMD_46_INDEX,
        PMBUS_CMD_47_INDEX,
        PMBUS_CMD_48_INDEX,
        PMBUS_CMD_49_INDEX,
        PMBUS_CMD_4A_INDEX,
        PMBUS_CMD_4B_INDEX,
        PMBUS_CMD_4C_INDEX,
        PMBUS_CMD_4D_INDEX,
        PMBUS_CMD_4E_INDEX,
        PMBUS_CMD_4F_INDEX,
        PMBUS_CMD_50_INDEX,
        PMBUS_CMD_51_INDEX,
        PMBUS_CMD_52_INDEX,
        PMBUS_CMD_53_INDEX,
        PMBUS_CMD_54_INDEX,
        PMBUS_CMD_55_INDEX,
        PMBUS_CMD_56_INDEX,
        PMBUS_CMD_57_INDEX,
        PMBUS_CMD_58_INDEX,
        PMBUS_CMD_59_INDEX,
        PMBUS_CMD_5A_INDEX,
        PMBUS_CMD_5B_INDEX,
        PMBUS_CMD_5C_INDEX,
        PMBUS_CMD_5D_INDEX,
        PMBUS_CMD_5E_INDEX,
        PMBUS_CMD_5F_INDEX,
        PMBUS_CMD_60_INDEX,
        PMBUS_CMD_61_INDEX,
        PMBUS_CMD_62_INDEX,
        PMBUS_CMD_63_INDEX,
        PMBUS_CMD_64_INDEX,
        PMBUS_CMD_65_INDEX,
        PMBUS_CMD_66_INDEX,
        PMBUS_CMD_67_INDEX,
        PMBUS_CMD_68_INDEX,
        PMBUS_CMD_69_INDEX,
        PMBUS_CMD_6A_INDEX,
        PMBUS_CMD_6B_INDEX,
        PMBUS_CMD_6C_INDEX,
        PMBUS_CMD_6D_INDEX,
        PMBUS_CMD_6E_INDEX,
        PMBUS_CMD_6F_INDEX,
        PMBUS_CMD_70_INDEX,
        PMBUS_CMD_71_INDEX,
        PMBUS_CMD_72_INDEX,
        PMBUS_CMD_73_INDEX,
        PMBUS_CMD_74_INDEX,
        PMBUS_CMD_75_INDEX,
        PMBUS_CMD_76_INDEX,
        PMBUS_CMD_77_INDEX,
        PMBUS_CMD_78_INDEX,
        PMBUS_CMD_79_INDEX,
        PMBUS_CMD_7A_INDEX,
        PMBUS_CMD_7B_INDEX,
        PMBUS_CMD_7C_INDEX,
        PMBUS_CMD_7D_INDEX,
        PMBUS_CMD_7E_INDEX,
        PMBUS_CMD_7F_INDEX,
        PMBUS_CMD_80_INDEX,
        PMBUS_CMD_81_INDEX,
        PMBUS_CMD_82_INDEX,
        PMBUS_CMD_83_INDEX,
        PMBUS_CMD_84_INDEX,
        PMBUS_CMD_85_INDEX,
        PMBUS_CMD_86_INDEX,
        PMBUS_CMD_87_INDEX,
        PMBUS_CMD_88_INDEX,
        PMBUS_CMD_89_INDEX,
        PMBUS_CMD_8A_INDEX,
        PMBUS_CMD_8B_INDEX,
        PMBUS_CMD_8C_INDEX,
        PMBUS_CMD_8D_INDEX,
        PMBUS_CMD_8E_INDEX,
        PMBUS_CMD_8F_INDEX,
        PMBUS_CMD_90_INDEX,
        PMBUS_CMD_91_INDEX,
        PMBUS_CMD_92_INDEX,
        PMBUS_CMD_93_INDEX,
        PMBUS_CMD_94_INDEX,
        PMBUS_CMD_95_INDEX,
        PMBUS_CMD_96_INDEX,
        PMBUS_CMD_97_INDEX,
        PMBUS_CMD_98_INDEX,
        PMBUS_CMD_99_INDEX,
        PMBUS_CMD_9A_INDEX,
        PMBUS_CMD_9B_INDEX,
        PMBUS_CMD_9C_INDEX,
        PMBUS_CMD_9D_INDEX,
        PMBUS_CMD_9E_INDEX,
        PMBUS_CMD_9F_INDEX,
        PMBUS_CMD_A0_INDEX,
        PMBUS_CMD_A1_INDEX,
        PMBUS_CMD_A2_INDEX,
        PMBUS_CMD_A3_INDEX,
        PMBUS_CMD_A4_INDEX,
        PMBUS_CMD_A5_INDEX,
        PMBUS_CMD_A6_INDEX,
        PMBUS_CMD_A7_INDEX,
        PMBUS_CMD_A8_INDEX,
        PMBUS_CMD_A9_INDEX,
        PMBUS_CMD_AA_INDEX,
        PMBUS_CMD_AB_INDEX,
        PMBUS_CMD_AC_INDEX,
        PMBUS_CMD_AD_INDEX,
        PMBUS_CMD_AE_INDEX,
        PMBUS_CMD_AF_INDEX,
        PMBUS_CMD_B0_INDEX,
        PMBUS_CMD_B1_INDEX,
        PMBUS_CMD_B2_INDEX,
        PMBUS_CMD_B3_INDEX,
        PMBUS_CMD_B4_INDEX,
        PMBUS_CMD_B5_INDEX,
        PMBUS_CMD_B6_INDEX,
        PMBUS_CMD_B7_INDEX,
        PMBUS_CMD_B8_INDEX,
        PMBUS_CMD_B9_INDEX,
        PMBUS_CMD_BA_INDEX,
        PMBUS_CMD_BB_INDEX,
        PMBUS_CMD_BC_INDEX,
        PMBUS_CMD_BD_INDEX,
        PMBUS_CMD_BE_INDEX,
        PMBUS_CMD_BF_INDEX,
        PMBUS_CMD_C0_INDEX,
        PMBUS_CMD_C1_INDEX,
        PMBUS_CMD_C2_INDEX,
        PMBUS_CMD_C3_INDEX,
        PMBUS_CMD_C4_INDEX,
        PMBUS_CMD_C5_INDEX,
        PMBUS_CMD_C6_INDEX,
        PMBUS_CMD_C7_INDEX,
        PMBUS_CMD_C8_INDEX,
        PMBUS_CMD_C9_INDEX,
        PMBUS_CMD_CA_INDEX,
        PMBUS_CMD_CB_INDEX,
        PMBUS_CMD_CC_INDEX,
        PMBUS_CMD_CD_INDEX,
        PMBUS_CMD_CE_INDEX,
        PMBUS_CMD_CF_INDEX,
        PMBUS_CMD_D0_INDEX,
        PMBUS_CMD_D1_INDEX,
        PMBUS_CMD_D2_INDEX,
        PMBUS_CMD_D3_INDEX,
        PMBUS_CMD_D4_INDEX,
        PMBUS_CMD_D5_INDEX,
        PMBUS_CMD_D6_INDEX,
        PMBUS_CMD_D7_INDEX,
        PMBUS_CMD_D8_INDEX,
        PMBUS_CMD_D9_INDEX,
        PMBUS_CMD_DA_INDEX,
        PMBUS_CMD_DB_INDEX,
        PMBUS_CMD_DC_INDEX,
        PMBUS_CMD_DD_INDEX,
        PMBUS_CMD_DE_INDEX,
        PMBUS_CMD_DF_INDEX,
        PMBUS_CMD_E0_INDEX,
        PMBUS_CMD_E1_INDEX,
        PMBUS_CMD_E2_INDEX,
        PMBUS_CMD_E3_INDEX,
        PMBUS_CMD_E4_INDEX,
        PMBUS_CMD_E5_INDEX,
        PMBUS_CMD_E6_INDEX,
        PMBUS_CMD_E7_INDEX,
        PMBUS_CMD_E8_INDEX,
        PMBUS_CMD_E9_INDEX,
        PMBUS_CMD_EA_INDEX,
        PMBUS_CMD_EB_INDEX,
        PMBUS_CMD_EC_INDEX,
        PMBUS_CMD_ED_INDEX,
        PMBUS_CMD_EE_INDEX,
        PMBUS_CMD_EF_INDEX,
        PMBUS_CMD_F0_INDEX,
        PMBUS_CMD_F1_INDEX,
        PMBUS_CMD_F2_INDEX,
        PMBUS_CMD_F3_INDEX,
        PMBUS_CMD_F4_INDEX,
        PMBUS_CMD_F5_INDEX,
        PMBUS_CMD_F6_INDEX,
        PMBUS_CMD_F7_INDEX,
        PMBUS_CMD_F8_INDEX,
        PMBUS_CMD_F9_INDEX,
        PMBUS_CMD_FA_INDEX,
        PMBUS_CMD_FB_INDEX,
        PMBUS_CMD_FC_INDEX,
        PMBUS_CMD_FD_INDEX,
        PMBUS_CMD_FE_INDEX,
        PMBUS_CMD_FF_INDEX,

};


typedef Uint8 (*PMBUS_READ_WRITE_FUNCTION_POINTER)(Uint8);
struct PMBUS_COMMANDS
{

	PMBUS_READ_WRITE_FUNCTION_POINTER pmbus_read_write_function_pointer;
	Uint8 query;
};

const struct PMBUS_COMMANDS pmbus_commands[] =
{
	{PMBUS_INVALID_COMMAND_FUNCTION_POINTER, PMBUS_INVALID_COMMAND_QUERY},
#if PMBUS_CMD_00_ENABLE
    {PMBUS_CMD_00_FUNCTION_POINTER , PMBUS_CMD_00_QUERY},
#endif
#if PMBUS_CMD_01_ENABLE
    {PMBUS_CMD_01_FUNCTION_POINTER , PMBUS_CMD_01_QUERY},
#endif
#if PMBUS_CMD_02_ENABLE
    {PMBUS_CMD_02_FUNCTION_POINTER , PMBUS_CMD_02_QUERY},
#endif
#if PMBUS_CMD_03_ENABLE
    {PMBUS_CMD_03_FUNCTION_POINTER , PMBUS_CMD_03_QUERY},
#endif
#if PMBUS_CMD_04_ENABLE
    {PMBUS_CMD_04_FUNCTION_POINTER , PMBUS_CMD_04_QUERY},
#endif
#if PMBUS_CMD_05_ENABLE
    {PMBUS_CMD_05_FUNCTION_POINTER , PMBUS_CMD_05_QUERY},
#endif
#if PMBUS_CMD_06_ENABLE
    {PMBUS_CMD_06_FUNCTION_POINTER , PMBUS_CMD_06_QUERY},
#endif
#if PMBUS_CMD_07_ENABLE
    {PMBUS_CMD_07_FUNCTION_POINTER , PMBUS_CMD_07_QUERY},
#endif
#if PMBUS_CMD_08_ENABLE
    {PMBUS_CMD_08_FUNCTION_POINTER , PMBUS_CMD_08_QUERY},
#endif
#if PMBUS_CMD_09_ENABLE
    {PMBUS_CMD_09_FUNCTION_POINTER , PMBUS_CMD_09_QUERY},
#endif
#if PMBUS_CMD_0A_ENABLE
    {PMBUS_CMD_0A_FUNCTION_POINTER , PMBUS_CMD_0A_QUERY},
#endif
#if PMBUS_CMD_0B_ENABLE
    {PMBUS_CMD_0B_FUNCTION_POINTER , PMBUS_CMD_0B_QUERY},
#endif
#if PMBUS_CMD_0C_ENABLE
    {PMBUS_CMD_0C_FUNCTION_POINTER , PMBUS_CMD_0C_QUERY},
#endif
#if PMBUS_CMD_0D_ENABLE
    {PMBUS_CMD_0D_FUNCTION_POINTER , PMBUS_CMD_0D_QUERY},
#endif
#if PMBUS_CMD_0E_ENABLE
    {PMBUS_CMD_0E_FUNCTION_POINTER , PMBUS_CMD_0E_QUERY},
#endif
#if PMBUS_CMD_0F_ENABLE
    {PMBUS_CMD_0F_FUNCTION_POINTER , PMBUS_CMD_0F_QUERY},
#endif
#if PMBUS_CMD_10_ENABLE
    {PMBUS_CMD_10_FUNCTION_POINTER , PMBUS_CMD_10_QUERY},
#endif
#if PMBUS_CMD_11_ENABLE
    {PMBUS_CMD_11_FUNCTION_POINTER , PMBUS_CMD_11_QUERY},
#endif
#if PMBUS_CMD_12_ENABLE
    {PMBUS_CMD_12_FUNCTION_POINTER , PMBUS_CMD_12_QUERY},
#endif
#if PMBUS_CMD_13_ENABLE
    {PMBUS_CMD_13_FUNCTION_POINTER , PMBUS_CMD_13_QUERY},
#endif
#if PMBUS_CMD_14_ENABLE
    {PMBUS_CMD_14_FUNCTION_POINTER , PMBUS_CMD_14_QUERY},
#endif
#if PMBUS_CMD_15_ENABLE
    {PMBUS_CMD_15_FUNCTION_POINTER , PMBUS_CMD_15_QUERY},
#endif
#if PMBUS_CMD_16_ENABLE
    {PMBUS_CMD_16_FUNCTION_POINTER , PMBUS_CMD_16_QUERY},
#endif
#if PMBUS_CMD_17_ENABLE
    {PMBUS_CMD_17_FUNCTION_POINTER , PMBUS_CMD_17_QUERY},
#endif
#if PMBUS_CMD_18_ENABLE
    {PMBUS_CMD_18_FUNCTION_POINTER , PMBUS_CMD_18_QUERY},
#endif
#if PMBUS_CMD_19_ENABLE
    {PMBUS_CMD_19_FUNCTION_POINTER , PMBUS_CMD_19_QUERY},
#endif
#if PMBUS_CMD_1A_ENABLE
    {PMBUS_CMD_1A_FUNCTION_POINTER , PMBUS_CMD_1A_QUERY},
#endif
#if PMBUS_CMD_1B_ENABLE
    {PMBUS_CMD_1B_FUNCTION_POINTER , PMBUS_CMD_1B_QUERY},
#endif
#if PMBUS_CMD_1C_ENABLE
    {PMBUS_CMD_1C_FUNCTION_POINTER , PMBUS_CMD_1C_QUERY},
#endif
#if PMBUS_CMD_1D_ENABLE
    {PMBUS_CMD_1D_FUNCTION_POINTER , PMBUS_CMD_1D_QUERY},
#endif
#if PMBUS_CMD_1E_ENABLE
    {PMBUS_CMD_1E_FUNCTION_POINTER , PMBUS_CMD_1E_QUERY},
#endif
#if PMBUS_CMD_1F_ENABLE
    {PMBUS_CMD_1F_FUNCTION_POINTER , PMBUS_CMD_1F_QUERY},
#endif
#if PMBUS_CMD_20_ENABLE
    {PMBUS_CMD_20_FUNCTION_POINTER , PMBUS_CMD_20_QUERY},
#endif
#if PMBUS_CMD_21_ENABLE
    {PMBUS_CMD_21_FUNCTION_POINTER , PMBUS_CMD_21_QUERY},
#endif
#if PMBUS_CMD_22_ENABLE
    {PMBUS_CMD_22_FUNCTION_POINTER , PMBUS_CMD_22_QUERY},
#endif
#if PMBUS_CMD_23_ENABLE
    {PMBUS_CMD_23_FUNCTION_POINTER , PMBUS_CMD_23_QUERY},
#endif
#if PMBUS_CMD_24_ENABLE
    {PMBUS_CMD_24_FUNCTION_POINTER , PMBUS_CMD_24_QUERY},
#endif
#if PMBUS_CMD_25_ENABLE
    {PMBUS_CMD_25_FUNCTION_POINTER , PMBUS_CMD_25_QUERY},
#endif
#if PMBUS_CMD_26_ENABLE
    {PMBUS_CMD_26_FUNCTION_POINTER , PMBUS_CMD_26_QUERY},
#endif
#if PMBUS_CMD_27_ENABLE
    {PMBUS_CMD_27_FUNCTION_POINTER , PMBUS_CMD_27_QUERY},
#endif
#if PMBUS_CMD_28_ENABLE
    {PMBUS_CMD_28_FUNCTION_POINTER , PMBUS_CMD_28_QUERY},
#endif
#if PMBUS_CMD_29_ENABLE
    {PMBUS_CMD_29_FUNCTION_POINTER , PMBUS_CMD_29_QUERY},
#endif
#if PMBUS_CMD_2A_ENABLE
    {PMBUS_CMD_2A_FUNCTION_POINTER , PMBUS_CMD_2A_QUERY},
#endif
#if PMBUS_CMD_2B_ENABLE
    {PMBUS_CMD_2B_FUNCTION_POINTER , PMBUS_CMD_2B_QUERY},
#endif
#if PMBUS_CMD_2C_ENABLE
    {PMBUS_CMD_2C_FUNCTION_POINTER , PMBUS_CMD_2C_QUERY},
#endif
#if PMBUS_CMD_2D_ENABLE
    {PMBUS_CMD_2D_FUNCTION_POINTER , PMBUS_CMD_2D_QUERY},
#endif
#if PMBUS_CMD_2E_ENABLE
    {PMBUS_CMD_2E_FUNCTION_POINTER , PMBUS_CMD_2E_QUERY},
#endif
#if PMBUS_CMD_2F_ENABLE
    {PMBUS_CMD_2F_FUNCTION_POINTER , PMBUS_CMD_2F_QUERY},
#endif
#if PMBUS_CMD_30_ENABLE
    {PMBUS_CMD_30_FUNCTION_POINTER , PMBUS_CMD_30_QUERY},
#endif
#if PMBUS_CMD_31_ENABLE
    {PMBUS_CMD_31_FUNCTION_POINTER , PMBUS_CMD_31_QUERY},
#endif
#if PMBUS_CMD_32_ENABLE
    {PMBUS_CMD_32_FUNCTION_POINTER , PMBUS_CMD_32_QUERY},
#endif
#if PMBUS_CMD_33_ENABLE
    {PMBUS_CMD_33_FUNCTION_POINTER , PMBUS_CMD_33_QUERY},
#endif
#if PMBUS_CMD_34_ENABLE
    {PMBUS_CMD_34_FUNCTION_POINTER , PMBUS_CMD_34_QUERY},
#endif
#if PMBUS_CMD_35_ENABLE
    {PMBUS_CMD_35_FUNCTION_POINTER , PMBUS_CMD_35_QUERY},
#endif
#if PMBUS_CMD_36_ENABLE
    {PMBUS_CMD_36_FUNCTION_POINTER , PMBUS_CMD_36_QUERY},
#endif
#if PMBUS_CMD_37_ENABLE
    {PMBUS_CMD_37_FUNCTION_POINTER , PMBUS_CMD_37_QUERY},
#endif
#if PMBUS_CMD_38_ENABLE
    {PMBUS_CMD_38_FUNCTION_POINTER , PMBUS_CMD_38_QUERY},
#endif
#if PMBUS_CMD_39_ENABLE
    {PMBUS_CMD_39_FUNCTION_POINTER , PMBUS_CMD_39_QUERY},
#endif
#if PMBUS_CMD_3A_ENABLE
    {PMBUS_CMD_3A_FUNCTION_POINTER , PMBUS_CMD_3A_QUERY},
#endif
#if PMBUS_CMD_3B_ENABLE
    {PMBUS_CMD_3B_FUNCTION_POINTER , PMBUS_CMD_3B_QUERY},
#endif
#if PMBUS_CMD_3C_ENABLE
    {PMBUS_CMD_3C_FUNCTION_POINTER , PMBUS_CMD_3C_QUERY},
#endif
#if PMBUS_CMD_3D_ENABLE
    {PMBUS_CMD_3D_FUNCTION_POINTER , PMBUS_CMD_3D_QUERY},
#endif
#if PMBUS_CMD_3E_ENABLE
    {PMBUS_CMD_3E_FUNCTION_POINTER , PMBUS_CMD_3E_QUERY},
#endif
#if PMBUS_CMD_3F_ENABLE
    {PMBUS_CMD_3F_FUNCTION_POINTER , PMBUS_CMD_3F_QUERY},
#endif
#if PMBUS_CMD_40_ENABLE
    {PMBUS_CMD_40_FUNCTION_POINTER , PMBUS_CMD_40_QUERY},
#endif
#if PMBUS_CMD_41_ENABLE
    {PMBUS_CMD_41_FUNCTION_POINTER , PMBUS_CMD_41_QUERY},
#endif
#if PMBUS_CMD_42_ENABLE
    {PMBUS_CMD_42_FUNCTION_POINTER , PMBUS_CMD_42_QUERY},
#endif
#if PMBUS_CMD_43_ENABLE
    {PMBUS_CMD_43_FUNCTION_POINTER , PMBUS_CMD_43_QUERY},
#endif
#if PMBUS_CMD_44_ENABLE
    {PMBUS_CMD_44_FUNCTION_POINTER , PMBUS_CMD_44_QUERY},
#endif
#if PMBUS_CMD_45_ENABLE
    {PMBUS_CMD_45_FUNCTION_POINTER , PMBUS_CMD_45_QUERY},
#endif
#if PMBUS_CMD_46_ENABLE
    {PMBUS_CMD_46_FUNCTION_POINTER , PMBUS_CMD_46_QUERY},
#endif
#if PMBUS_CMD_47_ENABLE
    {PMBUS_CMD_47_FUNCTION_POINTER , PMBUS_CMD_47_QUERY},
#endif
#if PMBUS_CMD_48_ENABLE
    {PMBUS_CMD_48_FUNCTION_POINTER , PMBUS_CMD_48_QUERY},
#endif
#if PMBUS_CMD_49_ENABLE
    {PMBUS_CMD_49_FUNCTION_POINTER , PMBUS_CMD_49_QUERY},
#endif
#if PMBUS_CMD_4A_ENABLE
    {PMBUS_CMD_4A_FUNCTION_POINTER , PMBUS_CMD_4A_QUERY},
#endif
#if PMBUS_CMD_4B_ENABLE
    {PMBUS_CMD_4B_FUNCTION_POINTER , PMBUS_CMD_4B_QUERY},
#endif
#if PMBUS_CMD_4C_ENABLE
    {PMBUS_CMD_4C_FUNCTION_POINTER , PMBUS_CMD_4C_QUERY},
#endif
#if PMBUS_CMD_4D_ENABLE
    {PMBUS_CMD_4D_FUNCTION_POINTER , PMBUS_CMD_4D_QUERY},
#endif
#if PMBUS_CMD_4E_ENABLE
    {PMBUS_CMD_4E_FUNCTION_POINTER , PMBUS_CMD_4E_QUERY},
#endif
#if PMBUS_CMD_4F_ENABLE
    {PMBUS_CMD_4F_FUNCTION_POINTER , PMBUS_CMD_4F_QUERY},
#endif
#if PMBUS_CMD_50_ENABLE
    {PMBUS_CMD_50_FUNCTION_POINTER , PMBUS_CMD_50_QUERY},
#endif
#if PMBUS_CMD_51_ENABLE
    {PMBUS_CMD_51_FUNCTION_POINTER , PMBUS_CMD_51_QUERY},
#endif
#if PMBUS_CMD_52_ENABLE
    {PMBUS_CMD_52_FUNCTION_POINTER , PMBUS_CMD_52_QUERY},
#endif
#if PMBUS_CMD_53_ENABLE
    {PMBUS_CMD_53_FUNCTION_POINTER , PMBUS_CMD_53_QUERY},
#endif
#if PMBUS_CMD_54_ENABLE
    {PMBUS_CMD_54_FUNCTION_POINTER , PMBUS_CMD_54_QUERY},
#endif
#if PMBUS_CMD_55_ENABLE
    {PMBUS_CMD_55_FUNCTION_POINTER , PMBUS_CMD_55_QUERY},
#endif
#if PMBUS_CMD_56_ENABLE
    {PMBUS_CMD_56_FUNCTION_POINTER , PMBUS_CMD_56_QUERY},
#endif
#if PMBUS_CMD_57_ENABLE
    {PMBUS_CMD_57_FUNCTION_POINTER , PMBUS_CMD_57_QUERY},
#endif
#if PMBUS_CMD_58_ENABLE
    {PMBUS_CMD_58_FUNCTION_POINTER , PMBUS_CMD_58_QUERY},
#endif
#if PMBUS_CMD_59_ENABLE
    {PMBUS_CMD_59_FUNCTION_POINTER , PMBUS_CMD_59_QUERY},
#endif
#if PMBUS_CMD_5A_ENABLE
    {PMBUS_CMD_5A_FUNCTION_POINTER , PMBUS_CMD_5A_QUERY},
#endif
#if PMBUS_CMD_5B_ENABLE
    {PMBUS_CMD_5B_FUNCTION_POINTER , PMBUS_CMD_5B_QUERY},
#endif
#if PMBUS_CMD_5C_ENABLE
    {PMBUS_CMD_5C_FUNCTION_POINTER , PMBUS_CMD_5C_QUERY},
#endif
#if PMBUS_CMD_5D_ENABLE
    {PMBUS_CMD_5D_FUNCTION_POINTER , PMBUS_CMD_5D_QUERY},
#endif
#if PMBUS_CMD_5E_ENABLE
    {PMBUS_CMD_5E_FUNCTION_POINTER , PMBUS_CMD_5E_QUERY},
#endif
#if PMBUS_CMD_5F_ENABLE
    {PMBUS_CMD_5F_FUNCTION_POINTER , PMBUS_CMD_5F_QUERY},
#endif
#if PMBUS_CMD_60_ENABLE
    {PMBUS_CMD_60_FUNCTION_POINTER , PMBUS_CMD_60_QUERY},
#endif
#if PMBUS_CMD_61_ENABLE
    {PMBUS_CMD_61_FUNCTION_POINTER , PMBUS_CMD_61_QUERY},
#endif
#if PMBUS_CMD_62_ENABLE
    {PMBUS_CMD_62_FUNCTION_POINTER , PMBUS_CMD_62_QUERY},
#endif
#if PMBUS_CMD_63_ENABLE
    {PMBUS_CMD_63_FUNCTION_POINTER , PMBUS_CMD_63_QUERY},
#endif
#if PMBUS_CMD_64_ENABLE
    {PMBUS_CMD_64_FUNCTION_POINTER , PMBUS_CMD_64_QUERY},
#endif
#if PMBUS_CMD_65_ENABLE
    {PMBUS_CMD_65_FUNCTION_POINTER , PMBUS_CMD_65_QUERY},
#endif
#if PMBUS_CMD_66_ENABLE
    {PMBUS_CMD_66_FUNCTION_POINTER , PMBUS_CMD_66_QUERY},
#endif
#if PMBUS_CMD_67_ENABLE
    {PMBUS_CMD_67_FUNCTION_POINTER , PMBUS_CMD_67_QUERY},
#endif
#if PMBUS_CMD_68_ENABLE
    {PMBUS_CMD_68_FUNCTION_POINTER , PMBUS_CMD_68_QUERY},
#endif
#if PMBUS_CMD_69_ENABLE
    {PMBUS_CMD_69_FUNCTION_POINTER , PMBUS_CMD_69_QUERY},
#endif
#if PMBUS_CMD_6A_ENABLE
    {PMBUS_CMD_6A_FUNCTION_POINTER , PMBUS_CMD_6A_QUERY},
#endif
#if PMBUS_CMD_6B_ENABLE
    {PMBUS_CMD_6B_FUNCTION_POINTER , PMBUS_CMD_6B_QUERY},
#endif
#if PMBUS_CMD_6C_ENABLE
    {PMBUS_CMD_6C_FUNCTION_POINTER , PMBUS_CMD_6C_QUERY},
#endif
#if PMBUS_CMD_6D_ENABLE
    {PMBUS_CMD_6D_FUNCTION_POINTER , PMBUS_CMD_6D_QUERY},
#endif
#if PMBUS_CMD_6E_ENABLE
    {PMBUS_CMD_6E_FUNCTION_POINTER , PMBUS_CMD_6E_QUERY},
#endif
#if PMBUS_CMD_6F_ENABLE
    {PMBUS_CMD_6F_FUNCTION_POINTER , PMBUS_CMD_6F_QUERY},
#endif
#if PMBUS_CMD_70_ENABLE
    {PMBUS_CMD_70_FUNCTION_POINTER , PMBUS_CMD_70_QUERY},
#endif
#if PMBUS_CMD_71_ENABLE
    {PMBUS_CMD_71_FUNCTION_POINTER , PMBUS_CMD_71_QUERY},
#endif
#if PMBUS_CMD_72_ENABLE
    {PMBUS_CMD_72_FUNCTION_POINTER , PMBUS_CMD_72_QUERY},
#endif
#if PMBUS_CMD_73_ENABLE
    {PMBUS_CMD_73_FUNCTION_POINTER , PMBUS_CMD_73_QUERY},
#endif
#if PMBUS_CMD_74_ENABLE
    {PMBUS_CMD_74_FUNCTION_POINTER , PMBUS_CMD_74_QUERY},
#endif
#if PMBUS_CMD_75_ENABLE
    {PMBUS_CMD_75_FUNCTION_POINTER , PMBUS_CMD_75_QUERY},
#endif
#if PMBUS_CMD_76_ENABLE
    {PMBUS_CMD_76_FUNCTION_POINTER , PMBUS_CMD_76_QUERY},
#endif
#if PMBUS_CMD_77_ENABLE
    {PMBUS_CMD_77_FUNCTION_POINTER , PMBUS_CMD_77_QUERY},
#endif
#if PMBUS_CMD_78_ENABLE
    {PMBUS_CMD_78_FUNCTION_POINTER , PMBUS_CMD_78_QUERY},
#endif
#if PMBUS_CMD_79_ENABLE
    {PMBUS_CMD_79_FUNCTION_POINTER , PMBUS_CMD_79_QUERY},
#endif
#if PMBUS_CMD_7A_ENABLE
    {PMBUS_CMD_7A_FUNCTION_POINTER , PMBUS_CMD_7A_QUERY},
#endif
#if PMBUS_CMD_7B_ENABLE
    {PMBUS_CMD_7B_FUNCTION_POINTER , PMBUS_CMD_7B_QUERY},
#endif
#if PMBUS_CMD_7C_ENABLE
    {PMBUS_CMD_7C_FUNCTION_POINTER , PMBUS_CMD_7C_QUERY},
#endif
#if PMBUS_CMD_7D_ENABLE
    {PMBUS_CMD_7D_FUNCTION_POINTER , PMBUS_CMD_7D_QUERY},
#endif
#if PMBUS_CMD_7E_ENABLE
    {PMBUS_CMD_7E_FUNCTION_POINTER , PMBUS_CMD_7E_QUERY},
#endif
#if PMBUS_CMD_7F_ENABLE
    {PMBUS_CMD_7F_FUNCTION_POINTER , PMBUS_CMD_7F_QUERY},
#endif
#if PMBUS_CMD_80_ENABLE
    {PMBUS_CMD_80_FUNCTION_POINTER , PMBUS_CMD_80_QUERY},
#endif
#if PMBUS_CMD_81_ENABLE
    {PMBUS_CMD_81_FUNCTION_POINTER , PMBUS_CMD_81_QUERY},
#endif
#if PMBUS_CMD_82_ENABLE
    {PMBUS_CMD_82_FUNCTION_POINTER , PMBUS_CMD_82_QUERY},
#endif
#if PMBUS_CMD_83_ENABLE
    {PMBUS_CMD_83_FUNCTION_POINTER , PMBUS_CMD_83_QUERY},
#endif
#if PMBUS_CMD_84_ENABLE
    {PMBUS_CMD_84_FUNCTION_POINTER , PMBUS_CMD_84_QUERY},
#endif
#if PMBUS_CMD_85_ENABLE
    {PMBUS_CMD_85_FUNCTION_POINTER , PMBUS_CMD_85_QUERY},
#endif
#if PMBUS_CMD_86_ENABLE
    {PMBUS_CMD_86_FUNCTION_POINTER , PMBUS_CMD_86_QUERY},
#endif
#if PMBUS_CMD_87_ENABLE
    {PMBUS_CMD_87_FUNCTION_POINTER , PMBUS_CMD_87_QUERY},
#endif
#if PMBUS_CMD_88_ENABLE
    {PMBUS_CMD_88_FUNCTION_POINTER , PMBUS_CMD_88_QUERY},
#endif
#if PMBUS_CMD_89_ENABLE
    {PMBUS_CMD_89_FUNCTION_POINTER , PMBUS_CMD_89_QUERY},
#endif
#if PMBUS_CMD_8A_ENABLE
    {PMBUS_CMD_8A_FUNCTION_POINTER , PMBUS_CMD_8A_QUERY},
#endif
#if PMBUS_CMD_8B_ENABLE
    {PMBUS_CMD_8B_FUNCTION_POINTER , PMBUS_CMD_8B_QUERY},
#endif
#if PMBUS_CMD_8C_ENABLE
    {PMBUS_CMD_8C_FUNCTION_POINTER , PMBUS_CMD_8C_QUERY},
#endif
#if PMBUS_CMD_8D_ENABLE
    {PMBUS_CMD_8D_FUNCTION_POINTER , PMBUS_CMD_8D_QUERY},
#endif
#if PMBUS_CMD_8E_ENABLE
    {PMBUS_CMD_8E_FUNCTION_POINTER , PMBUS_CMD_8E_QUERY},
#endif
#if PMBUS_CMD_8F_ENABLE
    {PMBUS_CMD_8F_FUNCTION_POINTER , PMBUS_CMD_8F_QUERY},
#endif
#if PMBUS_CMD_90_ENABLE
    {PMBUS_CMD_90_FUNCTION_POINTER , PMBUS_CMD_90_QUERY},
#endif
#if PMBUS_CMD_91_ENABLE
    {PMBUS_CMD_91_FUNCTION_POINTER , PMBUS_CMD_91_QUERY},
#endif
#if PMBUS_CMD_92_ENABLE
    {PMBUS_CMD_92_FUNCTION_POINTER , PMBUS_CMD_92_QUERY},
#endif
#if PMBUS_CMD_93_ENABLE
    {PMBUS_CMD_93_FUNCTION_POINTER , PMBUS_CMD_93_QUERY},
#endif
#if PMBUS_CMD_94_ENABLE
    {PMBUS_CMD_94_FUNCTION_POINTER , PMBUS_CMD_94_QUERY},
#endif
#if PMBUS_CMD_95_ENABLE
    {PMBUS_CMD_95_FUNCTION_POINTER , PMBUS_CMD_95_QUERY},
#endif
#if PMBUS_CMD_96_ENABLE
    {PMBUS_CMD_96_FUNCTION_POINTER , PMBUS_CMD_96_QUERY},
#endif
#if PMBUS_CMD_97_ENABLE
    {PMBUS_CMD_97_FUNCTION_POINTER , PMBUS_CMD_97_QUERY},
#endif
#if PMBUS_CMD_98_ENABLE
    {PMBUS_CMD_98_FUNCTION_POINTER , PMBUS_CMD_98_QUERY},
#endif
#if PMBUS_CMD_99_ENABLE
    {PMBUS_CMD_99_FUNCTION_POINTER , PMBUS_CMD_99_QUERY},
#endif
#if PMBUS_CMD_9A_ENABLE
    {PMBUS_CMD_9A_FUNCTION_POINTER , PMBUS_CMD_9A_QUERY},
#endif
#if PMBUS_CMD_9B_ENABLE
    {PMBUS_CMD_9B_FUNCTION_POINTER , PMBUS_CMD_9B_QUERY},
#endif
#if PMBUS_CMD_9C_ENABLE
    {PMBUS_CMD_9C_FUNCTION_POINTER , PMBUS_CMD_9C_QUERY},
#endif
#if PMBUS_CMD_9D_ENABLE
    {PMBUS_CMD_9D_FUNCTION_POINTER , PMBUS_CMD_9D_QUERY},
#endif
#if PMBUS_CMD_9E_ENABLE
    {PMBUS_CMD_9E_FUNCTION_POINTER , PMBUS_CMD_9E_QUERY},
#endif
#if PMBUS_CMD_9F_ENABLE
    {PMBUS_CMD_9F_FUNCTION_POINTER , PMBUS_CMD_9F_QUERY},
#endif
#if PMBUS_CMD_A0_ENABLE
    {PMBUS_CMD_A0_FUNCTION_POINTER , PMBUS_CMD_A0_QUERY},
#endif
#if PMBUS_CMD_A1_ENABLE
    {PMBUS_CMD_A1_FUNCTION_POINTER , PMBUS_CMD_A1_QUERY},
#endif
#if PMBUS_CMD_A2_ENABLE
    {PMBUS_CMD_A2_FUNCTION_POINTER , PMBUS_CMD_A2_QUERY},
#endif
#if PMBUS_CMD_A3_ENABLE
    {PMBUS_CMD_A3_FUNCTION_POINTER , PMBUS_CMD_A3_QUERY},
#endif
#if PMBUS_CMD_A4_ENABLE
    {PMBUS_CMD_A4_FUNCTION_POINTER , PMBUS_CMD_A4_QUERY},
#endif
#if PMBUS_CMD_A5_ENABLE
    {PMBUS_CMD_A5_FUNCTION_POINTER , PMBUS_CMD_A5_QUERY},
#endif
#if PMBUS_CMD_A6_ENABLE
    {PMBUS_CMD_A6_FUNCTION_POINTER , PMBUS_CMD_A6_QUERY},
#endif
#if PMBUS_CMD_A7_ENABLE
    {PMBUS_CMD_A7_FUNCTION_POINTER , PMBUS_CMD_A7_QUERY},
#endif
#if PMBUS_CMD_A8_ENABLE
    {PMBUS_CMD_A8_FUNCTION_POINTER , PMBUS_CMD_A8_QUERY},
#endif
#if PMBUS_CMD_A9_ENABLE
    {PMBUS_CMD_A9_FUNCTION_POINTER , PMBUS_CMD_A9_QUERY},
#endif
#if PMBUS_CMD_AA_ENABLE
    {PMBUS_CMD_AA_FUNCTION_POINTER , PMBUS_CMD_AA_QUERY},
#endif
#if PMBUS_CMD_AB_ENABLE
    {PMBUS_CMD_AB_FUNCTION_POINTER , PMBUS_CMD_AB_QUERY},
#endif
#if PMBUS_CMD_AC_ENABLE
    {PMBUS_CMD_AC_FUNCTION_POINTER , PMBUS_CMD_AC_QUERY},
#endif
#if PMBUS_CMD_AD_ENABLE
    {PMBUS_CMD_AD_FUNCTION_POINTER , PMBUS_CMD_AD_QUERY},
#endif
#if PMBUS_CMD_AE_ENABLE
    {PMBUS_CMD_AE_FUNCTION_POINTER , PMBUS_CMD_AE_QUERY},
#endif
#if PMBUS_CMD_AF_ENABLE
    {PMBUS_CMD_AF_FUNCTION_POINTER , PMBUS_CMD_AF_QUERY},
#endif
#if PMBUS_CMD_B0_ENABLE
    {PMBUS_CMD_B0_FUNCTION_POINTER , PMBUS_CMD_B0_QUERY},
#endif
#if PMBUS_CMD_B1_ENABLE
    {PMBUS_CMD_B1_FUNCTION_POINTER , PMBUS_CMD_B1_QUERY},
#endif
#if PMBUS_CMD_B2_ENABLE
    {PMBUS_CMD_B2_FUNCTION_POINTER , PMBUS_CMD_B2_QUERY},
#endif
#if PMBUS_CMD_B3_ENABLE
    {PMBUS_CMD_B3_FUNCTION_POINTER , PMBUS_CMD_B3_QUERY},
#endif
#if PMBUS_CMD_B4_ENABLE
    {PMBUS_CMD_B4_FUNCTION_POINTER , PMBUS_CMD_B4_QUERY},
#endif
#if PMBUS_CMD_B5_ENABLE
    {PMBUS_CMD_B5_FUNCTION_POINTER , PMBUS_CMD_B5_QUERY},
#endif
#if PMBUS_CMD_B6_ENABLE
    {PMBUS_CMD_B6_FUNCTION_POINTER , PMBUS_CMD_B6_QUERY},
#endif
#if PMBUS_CMD_B7_ENABLE
    {PMBUS_CMD_B7_FUNCTION_POINTER , PMBUS_CMD_B7_QUERY},
#endif
#if PMBUS_CMD_B8_ENABLE
    {PMBUS_CMD_B8_FUNCTION_POINTER , PMBUS_CMD_B8_QUERY},
#endif
#if PMBUS_CMD_B9_ENABLE
    {PMBUS_CMD_B9_FUNCTION_POINTER , PMBUS_CMD_B9_QUERY},
#endif
#if PMBUS_CMD_BA_ENABLE
    {PMBUS_CMD_BA_FUNCTION_POINTER , PMBUS_CMD_BA_QUERY},
#endif
#if PMBUS_CMD_BB_ENABLE
    {PMBUS_CMD_BB_FUNCTION_POINTER , PMBUS_CMD_BB_QUERY},
#endif
#if PMBUS_CMD_BC_ENABLE
    {PMBUS_CMD_BC_FUNCTION_POINTER , PMBUS_CMD_BC_QUERY},
#endif
#if PMBUS_CMD_BD_ENABLE
    {PMBUS_CMD_BD_FUNCTION_POINTER , PMBUS_CMD_BD_QUERY},
#endif
#if PMBUS_CMD_BE_ENABLE
    {PMBUS_CMD_BE_FUNCTION_POINTER , PMBUS_CMD_BE_QUERY},
#endif
#if PMBUS_CMD_BF_ENABLE
    {PMBUS_CMD_BF_FUNCTION_POINTER , PMBUS_CMD_BF_QUERY},
#endif
#if PMBUS_CMD_C0_ENABLE
    {PMBUS_CMD_C0_FUNCTION_POINTER , PMBUS_CMD_C0_QUERY},
#endif
#if PMBUS_CMD_C1_ENABLE
    {PMBUS_CMD_C1_FUNCTION_POINTER , PMBUS_CMD_C1_QUERY},
#endif
#if PMBUS_CMD_C2_ENABLE
    {PMBUS_CMD_C2_FUNCTION_POINTER , PMBUS_CMD_C2_QUERY},
#endif
#if PMBUS_CMD_C3_ENABLE
    {PMBUS_CMD_C3_FUNCTION_POINTER , PMBUS_CMD_C3_QUERY},
#endif
#if PMBUS_CMD_C4_ENABLE
    {PMBUS_CMD_C4_FUNCTION_POINTER , PMBUS_CMD_C4_QUERY},
#endif
#if PMBUS_CMD_C5_ENABLE
    {PMBUS_CMD_C5_FUNCTION_POINTER , PMBUS_CMD_C5_QUERY},
#endif
#if PMBUS_CMD_C6_ENABLE
    {PMBUS_CMD_C6_FUNCTION_POINTER , PMBUS_CMD_C6_QUERY},
#endif
#if PMBUS_CMD_C7_ENABLE
    {PMBUS_CMD_C7_FUNCTION_POINTER , PMBUS_CMD_C7_QUERY},
#endif
#if PMBUS_CMD_C8_ENABLE
    {PMBUS_CMD_C8_FUNCTION_POINTER , PMBUS_CMD_C8_QUERY},
#endif
#if PMBUS_CMD_C9_ENABLE
    {PMBUS_CMD_C9_FUNCTION_POINTER , PMBUS_CMD_C9_QUERY},
#endif
#if PMBUS_CMD_CA_ENABLE
    {PMBUS_CMD_CA_FUNCTION_POINTER , PMBUS_CMD_CA_QUERY},
#endif
#if PMBUS_CMD_CB_ENABLE
    {PMBUS_CMD_CB_FUNCTION_POINTER , PMBUS_CMD_CB_QUERY},
#endif
#if PMBUS_CMD_CC_ENABLE
    {PMBUS_CMD_CC_FUNCTION_POINTER , PMBUS_CMD_CC_QUERY},
#endif
#if PMBUS_CMD_CD_ENABLE
    {PMBUS_CMD_CD_FUNCTION_POINTER , PMBUS_CMD_CD_QUERY},
#endif
#if PMBUS_CMD_CE_ENABLE
    {PMBUS_CMD_CE_FUNCTION_POINTER , PMBUS_CMD_CE_QUERY},
#endif
#if PMBUS_CMD_CF_ENABLE
    {PMBUS_CMD_CF_FUNCTION_POINTER , PMBUS_CMD_CF_QUERY},
#endif
#if PMBUS_CMD_D0_ENABLE
    {PMBUS_CMD_D0_FUNCTION_POINTER , PMBUS_CMD_D0_QUERY},
#endif
#if PMBUS_CMD_D1_ENABLE
    {PMBUS_CMD_D1_FUNCTION_POINTER , PMBUS_CMD_D1_QUERY},
#endif
#if PMBUS_CMD_D2_ENABLE
    {PMBUS_CMD_D2_FUNCTION_POINTER , PMBUS_CMD_D2_QUERY},
#endif
#if PMBUS_CMD_D3_ENABLE
    {PMBUS_CMD_D3_FUNCTION_POINTER , PMBUS_CMD_D3_QUERY},
#endif
#if PMBUS_CMD_D4_ENABLE
    {PMBUS_CMD_D4_FUNCTION_POINTER , PMBUS_CMD_D4_QUERY},
#endif
#if PMBUS_CMD_D5_ENABLE
    {PMBUS_CMD_D5_FUNCTION_POINTER , PMBUS_CMD_D5_QUERY},
#endif
#if PMBUS_CMD_D6_ENABLE
    {PMBUS_CMD_D6_FUNCTION_POINTER , PMBUS_CMD_D6_QUERY},
#endif
#if PMBUS_CMD_D7_ENABLE
    {PMBUS_CMD_D7_FUNCTION_POINTER , PMBUS_CMD_D7_QUERY},
#endif
#if PMBUS_CMD_D8_ENABLE
    {PMBUS_CMD_D8_FUNCTION_POINTER , PMBUS_CMD_D8_QUERY},
#endif
#if PMBUS_CMD_D9_ENABLE
    {PMBUS_CMD_D9_FUNCTION_POINTER , PMBUS_CMD_D9_QUERY},
#endif
#if PMBUS_CMD_DA_ENABLE
    {PMBUS_CMD_DA_FUNCTION_POINTER , PMBUS_CMD_DA_QUERY},
#endif
#if PMBUS_CMD_DB_ENABLE
    {PMBUS_CMD_DB_FUNCTION_POINTER , PMBUS_CMD_DB_QUERY},
#endif
#if PMBUS_CMD_DC_ENABLE
    {PMBUS_CMD_DC_FUNCTION_POINTER , PMBUS_CMD_DC_QUERY},
#endif
#if PMBUS_CMD_DD_ENABLE
    {PMBUS_CMD_DD_FUNCTION_POINTER , PMBUS_CMD_DD_QUERY},
#endif
#if PMBUS_CMD_DE_ENABLE
    {PMBUS_CMD_DE_FUNCTION_POINTER , PMBUS_CMD_DE_QUERY},
#endif
#if PMBUS_CMD_DF_ENABLE
    {PMBUS_CMD_DF_FUNCTION_POINTER , PMBUS_CMD_DF_QUERY},
#endif
#if PMBUS_CMD_E0_ENABLE
    {PMBUS_CMD_E0_FUNCTION_POINTER , PMBUS_CMD_E0_QUERY},
#endif
#if PMBUS_CMD_E1_ENABLE
    {PMBUS_CMD_E1_FUNCTION_POINTER , PMBUS_CMD_E1_QUERY},
#endif
#if PMBUS_CMD_E2_ENABLE
    {PMBUS_CMD_E2_FUNCTION_POINTER , PMBUS_CMD_E2_QUERY},
#endif
#if PMBUS_CMD_E3_ENABLE
    {PMBUS_CMD_E3_FUNCTION_POINTER , PMBUS_CMD_E3_QUERY},
#endif
#if PMBUS_CMD_E4_ENABLE
    {PMBUS_CMD_E4_FUNCTION_POINTER , PMBUS_CMD_E4_QUERY},
#endif
#if PMBUS_CMD_E5_ENABLE
    {PMBUS_CMD_E5_FUNCTION_POINTER , PMBUS_CMD_E5_QUERY},
#endif
#if PMBUS_CMD_E6_ENABLE
    {PMBUS_CMD_E6_FUNCTION_POINTER , PMBUS_CMD_E6_QUERY},
#endif
#if PMBUS_CMD_E7_ENABLE
    {PMBUS_CMD_E7_FUNCTION_POINTER , PMBUS_CMD_E7_QUERY},
#endif
#if PMBUS_CMD_E8_ENABLE
    {PMBUS_CMD_E8_FUNCTION_POINTER , PMBUS_CMD_E8_QUERY},
#endif
#if PMBUS_CMD_E9_ENABLE
    {PMBUS_CMD_E9_FUNCTION_POINTER , PMBUS_CMD_E9_QUERY},
#endif
#if PMBUS_CMD_EA_ENABLE
    {PMBUS_CMD_EA_FUNCTION_POINTER , PMBUS_CMD_EA_QUERY},
#endif
#if PMBUS_CMD_EB_ENABLE
    {PMBUS_CMD_EB_FUNCTION_POINTER , PMBUS_CMD_EB_QUERY},
#endif
#if PMBUS_CMD_EC_ENABLE
    {PMBUS_CMD_EC_FUNCTION_POINTER , PMBUS_CMD_EC_QUERY},
#endif
#if PMBUS_CMD_ED_ENABLE
    {PMBUS_CMD_ED_FUNCTION_POINTER , PMBUS_CMD_ED_QUERY},
#endif
#if PMBUS_CMD_EE_ENABLE
    {PMBUS_CMD_EE_FUNCTION_POINTER , PMBUS_CMD_EE_QUERY},
#endif
#if PMBUS_CMD_EF_ENABLE
    {PMBUS_CMD_EF_FUNCTION_POINTER , PMBUS_CMD_EF_QUERY},
#endif
#if PMBUS_CMD_F0_ENABLE
    {PMBUS_CMD_F0_FUNCTION_POINTER , PMBUS_CMD_F0_QUERY},
#endif
#if PMBUS_CMD_F1_ENABLE
    {PMBUS_CMD_F1_FUNCTION_POINTER , PMBUS_CMD_F1_QUERY},
#endif
#if PMBUS_CMD_F2_ENABLE
    {PMBUS_CMD_F2_FUNCTION_POINTER , PMBUS_CMD_F2_QUERY},
#endif
#if PMBUS_CMD_F3_ENABLE
    {PMBUS_CMD_F3_FUNCTION_POINTER , PMBUS_CMD_F3_QUERY},
#endif
#if PMBUS_CMD_F4_ENABLE
    {PMBUS_CMD_F4_FUNCTION_POINTER , PMBUS_CMD_F4_QUERY},
#endif
#if PMBUS_CMD_F5_ENABLE
    {PMBUS_CMD_F5_FUNCTION_POINTER , PMBUS_CMD_F5_QUERY},
#endif
#if PMBUS_CMD_F6_ENABLE
    {PMBUS_CMD_F6_FUNCTION_POINTER , PMBUS_CMD_F6_QUERY},
#endif
#if PMBUS_CMD_F7_ENABLE
    {PMBUS_CMD_F7_FUNCTION_POINTER , PMBUS_CMD_F7_QUERY},
#endif
#if PMBUS_CMD_F8_ENABLE
    {PMBUS_CMD_F8_FUNCTION_POINTER , PMBUS_CMD_F8_QUERY},
#endif
#if PMBUS_CMD_F9_ENABLE
    {PMBUS_CMD_F9_FUNCTION_POINTER , PMBUS_CMD_F9_QUERY},
#endif
#if PMBUS_CMD_FA_ENABLE
    {PMBUS_CMD_FA_FUNCTION_POINTER , PMBUS_CMD_FA_QUERY},
#endif
#if PMBUS_CMD_FB_ENABLE
    {PMBUS_CMD_FB_FUNCTION_POINTER , PMBUS_CMD_FB_QUERY},
#endif
#if PMBUS_CMD_FC_ENABLE
    {PMBUS_CMD_FC_FUNCTION_POINTER , PMBUS_CMD_FC_QUERY},
#endif
#if PMBUS_CMD_FD_ENABLE
    {PMBUS_CMD_FD_FUNCTION_POINTER , PMBUS_CMD_FD_QUERY},
#endif
#if PMBUS_CMD_FE_ENABLE
    {PMBUS_CMD_FE_FUNCTION_POINTER , PMBUS_CMD_FE_QUERY},
#endif
#if PMBUS_CMD_FF_ENABLE
    {PMBUS_CMD_FF_FUNCTION_POINTER , PMBUS_CMD_FF_QUERY},
#endif
};

#define CMD_00_TO_07_BITS_MASK  (Uint8)((PMBUS_CMD_00_ENABLE<<7)|(PMBUS_CMD_01_ENABLE<<6)|(PMBUS_CMD_02_ENABLE<<5)|(PMBUS_CMD_03_ENABLE<<4)|\
							    		(PMBUS_CMD_04_ENABLE<<3)|(PMBUS_CMD_05_ENABLE<<2)|(PMBUS_CMD_06_ENABLE<<1)|(PMBUS_CMD_07_ENABLE<<0))\

#define CMD_08_TO_0F_BITS_MASK  (Uint8)((PMBUS_CMD_08_ENABLE<<7)|(PMBUS_CMD_09_ENABLE<<6)|(PMBUS_CMD_0A_ENABLE<<5)|(PMBUS_CMD_0B_ENABLE<<4)|\
								 	 	(PMBUS_CMD_0C_ENABLE<<3)|(PMBUS_CMD_0D_ENABLE<<2)|(PMBUS_CMD_0E_ENABLE<<1)|(PMBUS_CMD_0F_ENABLE<<0))\

#define CMD_10_TO_17_BITS_MASK  (Uint8)((PMBUS_CMD_10_ENABLE<<7)|(PMBUS_CMD_11_ENABLE<<6)|(PMBUS_CMD_12_ENABLE<<5)|(PMBUS_CMD_13_ENABLE<<4)|\
							    		(PMBUS_CMD_14_ENABLE<<3)|(PMBUS_CMD_15_ENABLE<<2)|(PMBUS_CMD_16_ENABLE<<1)|(PMBUS_CMD_17_ENABLE<<0))\

#define CMD_18_TO_1F_BITS_MASK  (Uint8)((PMBUS_CMD_18_ENABLE<<7)|(PMBUS_CMD_19_ENABLE<<6)|(PMBUS_CMD_1A_ENABLE<<5)|(PMBUS_CMD_1B_ENABLE<<4)|\
								 	 	(PMBUS_CMD_1C_ENABLE<<3)|(PMBUS_CMD_1D_ENABLE<<2)|(PMBUS_CMD_1E_ENABLE<<1)|(PMBUS_CMD_1F_ENABLE<<0))\

#define CMD_20_TO_27_BITS_MASK  (Uint8)((PMBUS_CMD_20_ENABLE<<7)|(PMBUS_CMD_21_ENABLE<<6)|(PMBUS_CMD_22_ENABLE<<5)|(PMBUS_CMD_23_ENABLE<<4)|\
							    		(PMBUS_CMD_24_ENABLE<<3)|(PMBUS_CMD_25_ENABLE<<2)|(PMBUS_CMD_26_ENABLE<<1)|(PMBUS_CMD_27_ENABLE<<0))\

#define CMD_28_TO_2F_BITS_MASK  (Uint8)((PMBUS_CMD_28_ENABLE<<7)|(PMBUS_CMD_29_ENABLE<<6)|(PMBUS_CMD_2A_ENABLE<<5)|(PMBUS_CMD_2B_ENABLE<<4)|\
								 	 	(PMBUS_CMD_2C_ENABLE<<3)|(PMBUS_CMD_2D_ENABLE<<2)|(PMBUS_CMD_2E_ENABLE<<1)|(PMBUS_CMD_2F_ENABLE<<0))\

#define CMD_30_TO_37_BITS_MASK  (Uint8)((PMBUS_CMD_30_ENABLE<<7)|(PMBUS_CMD_31_ENABLE<<6)|(PMBUS_CMD_32_ENABLE<<5)|(PMBUS_CMD_33_ENABLE<<4)|\
							    		(PMBUS_CMD_34_ENABLE<<3)|(PMBUS_CMD_35_ENABLE<<2)|(PMBUS_CMD_36_ENABLE<<1)|(PMBUS_CMD_37_ENABLE<<0))\

#define CMD_38_TO_3F_BITS_MASK  (Uint8)((PMBUS_CMD_38_ENABLE<<7)|(PMBUS_CMD_39_ENABLE<<6)|(PMBUS_CMD_3A_ENABLE<<5)|(PMBUS_CMD_3B_ENABLE<<4)|\
								 	 	(PMBUS_CMD_3C_ENABLE<<3)|(PMBUS_CMD_3D_ENABLE<<2)|(PMBUS_CMD_3E_ENABLE<<1)|(PMBUS_CMD_3F_ENABLE<<0))\

#define CMD_40_TO_47_BITS_MASK  (Uint8)((PMBUS_CMD_40_ENABLE<<7)|(PMBUS_CMD_41_ENABLE<<6)|(PMBUS_CMD_42_ENABLE<<5)|(PMBUS_CMD_43_ENABLE<<4)|\
							    		(PMBUS_CMD_44_ENABLE<<3)|(PMBUS_CMD_45_ENABLE<<2)|(PMBUS_CMD_46_ENABLE<<1)|(PMBUS_CMD_47_ENABLE<<0))\

#define CMD_48_TO_4F_BITS_MASK  (Uint8)((PMBUS_CMD_48_ENABLE<<7)|(PMBUS_CMD_49_ENABLE<<6)|(PMBUS_CMD_4A_ENABLE<<5)|(PMBUS_CMD_4B_ENABLE<<4)|\
								 	 	(PMBUS_CMD_4C_ENABLE<<3)|(PMBUS_CMD_4D_ENABLE<<2)|(PMBUS_CMD_4E_ENABLE<<1)|(PMBUS_CMD_4F_ENABLE<<0))\

#define CMD_50_TO_57_BITS_MASK  (Uint8)((PMBUS_CMD_50_ENABLE<<7)|(PMBUS_CMD_51_ENABLE<<6)|(PMBUS_CMD_52_ENABLE<<5)|(PMBUS_CMD_53_ENABLE<<4)|\
							   	   	    (PMBUS_CMD_54_ENABLE<<3)|(PMBUS_CMD_55_ENABLE<<2)|(PMBUS_CMD_56_ENABLE<<1)|(PMBUS_CMD_57_ENABLE<<0))\

#define CMD_58_TO_5F_BITS_MASK  (Uint8)((PMBUS_CMD_58_ENABLE<<7)|(PMBUS_CMD_59_ENABLE<<6)|(PMBUS_CMD_5A_ENABLE<<5)|(PMBUS_CMD_5B_ENABLE<<4)|\
								 	 	(PMBUS_CMD_5C_ENABLE<<3)|(PMBUS_CMD_5D_ENABLE<<2)|(PMBUS_CMD_5E_ENABLE<<1)|(PMBUS_CMD_5F_ENABLE<<0))\

#define CMD_60_TO_67_BITS_MASK  (Uint8)((PMBUS_CMD_60_ENABLE<<7)|(PMBUS_CMD_61_ENABLE<<6)|(PMBUS_CMD_62_ENABLE<<5)|(PMBUS_CMD_63_ENABLE<<4)|\
							   	   	    (PMBUS_CMD_64_ENABLE<<3)|(PMBUS_CMD_65_ENABLE<<2)|(PMBUS_CMD_66_ENABLE<<1)|(PMBUS_CMD_67_ENABLE<<0))\

#define CMD_68_TO_6F_BITS_MASK  (Uint8)((PMBUS_CMD_68_ENABLE<<7)|(PMBUS_CMD_69_ENABLE<<6)|(PMBUS_CMD_6A_ENABLE<<5)|(PMBUS_CMD_6B_ENABLE<<4)|\
								 	 	(PMBUS_CMD_6C_ENABLE<<3)|(PMBUS_CMD_6D_ENABLE<<2)|(PMBUS_CMD_6E_ENABLE<<1)|(PMBUS_CMD_6F_ENABLE<<0))\

#define CMD_70_TO_77_BITS_MASK  (Uint8)((PMBUS_CMD_70_ENABLE<<7)|(PMBUS_CMD_71_ENABLE<<6)|(PMBUS_CMD_72_ENABLE<<5)|(PMBUS_CMD_73_ENABLE<<4)|\
							   	   	   	(PMBUS_CMD_74_ENABLE<<3)|(PMBUS_CMD_75_ENABLE<<2)|(PMBUS_CMD_76_ENABLE<<1)|(PMBUS_CMD_77_ENABLE<<0))\

#define CMD_78_TO_7F_BITS_MASK  (Uint8)((PMBUS_CMD_78_ENABLE<<7)|(PMBUS_CMD_79_ENABLE<<6)|(PMBUS_CMD_7A_ENABLE<<5)|(PMBUS_CMD_7B_ENABLE<<4)|\
								 	    (PMBUS_CMD_7C_ENABLE<<3)|(PMBUS_CMD_7D_ENABLE<<2)|(PMBUS_CMD_7E_ENABLE<<1)|(PMBUS_CMD_7F_ENABLE<<0))\

#define CMD_80_TO_87_BITS_MASK  (Uint8)((PMBUS_CMD_80_ENABLE<<7)|(PMBUS_CMD_81_ENABLE<<6)|(PMBUS_CMD_82_ENABLE<<5)|(PMBUS_CMD_83_ENABLE<<4)|\
							   	   	    (PMBUS_CMD_84_ENABLE<<3)|(PMBUS_CMD_85_ENABLE<<2)|(PMBUS_CMD_86_ENABLE<<1)|(PMBUS_CMD_87_ENABLE<<0))\

#define CMD_88_TO_8F_BITS_MASK  (Uint8)((PMBUS_CMD_88_ENABLE<<7)|(PMBUS_CMD_89_ENABLE<<6)|(PMBUS_CMD_8A_ENABLE<<5)|(PMBUS_CMD_8B_ENABLE<<4)|\
								 	 	(PMBUS_CMD_8C_ENABLE<<3)|(PMBUS_CMD_8D_ENABLE<<2)|(PMBUS_CMD_8E_ENABLE<<1)|(PMBUS_CMD_8F_ENABLE<<0))\

#define CMD_90_TO_97_BITS_MASK  (Uint8)((PMBUS_CMD_90_ENABLE<<7)|(PMBUS_CMD_91_ENABLE<<6)|(PMBUS_CMD_92_ENABLE<<5)|(PMBUS_CMD_93_ENABLE<<4)|\
							   	   	    (PMBUS_CMD_94_ENABLE<<3)|(PMBUS_CMD_95_ENABLE<<2)|(PMBUS_CMD_96_ENABLE<<1)|(PMBUS_CMD_97_ENABLE<<0))\

#define CMD_98_TO_9F_BITS_MASK  (Uint8)((PMBUS_CMD_98_ENABLE<<7)|(PMBUS_CMD_99_ENABLE<<6)|(PMBUS_CMD_9A_ENABLE<<5)|(PMBUS_CMD_9B_ENABLE<<4)|\
								 	 	(PMBUS_CMD_9C_ENABLE<<3)|(PMBUS_CMD_9D_ENABLE<<2)|(PMBUS_CMD_9E_ENABLE<<1)|(PMBUS_CMD_9F_ENABLE<<0))\

#define CMD_A0_TO_A7_BITS_MASK  (Uint8)((PMBUS_CMD_A0_ENABLE<<7)|(PMBUS_CMD_A1_ENABLE<<6)|(PMBUS_CMD_A2_ENABLE<<5)|(PMBUS_CMD_A3_ENABLE<<4)|\
							   	   	    (PMBUS_CMD_A4_ENABLE<<3)|(PMBUS_CMD_A5_ENABLE<<2)|(PMBUS_CMD_A6_ENABLE<<1)|(PMBUS_CMD_A7_ENABLE<<0))\

#define CMD_A8_TO_AF_BITS_MASK  (Uint8)((PMBUS_CMD_A8_ENABLE<<7)|(PMBUS_CMD_A9_ENABLE<<6)|(PMBUS_CMD_AA_ENABLE<<5)|(PMBUS_CMD_AB_ENABLE<<4)|\
								 	 	(PMBUS_CMD_AC_ENABLE<<3)|(PMBUS_CMD_AD_ENABLE<<2)|(PMBUS_CMD_AE_ENABLE<<1)|(PMBUS_CMD_AF_ENABLE<<0))\

#define CMD_B0_TO_B7_BITS_MASK  (Uint8)((PMBUS_CMD_B0_ENABLE<<7)|(PMBUS_CMD_B1_ENABLE<<6)|(PMBUS_CMD_B2_ENABLE<<5)|(PMBUS_CMD_B3_ENABLE<<4)|\
							   	   	    (PMBUS_CMD_B4_ENABLE<<3)|(PMBUS_CMD_B5_ENABLE<<2)|(PMBUS_CMD_B6_ENABLE<<1)|(PMBUS_CMD_B7_ENABLE<<0))\

#define CMD_B8_TO_BF_BITS_MASK  (Uint8)((PMBUS_CMD_B8_ENABLE<<7)|(PMBUS_CMD_B9_ENABLE<<6)|(PMBUS_CMD_BA_ENABLE<<5)|(PMBUS_CMD_BB_ENABLE<<4)|\
								 	 	(PMBUS_CMD_BC_ENABLE<<3)|(PMBUS_CMD_BD_ENABLE<<2)|(PMBUS_CMD_BE_ENABLE<<1)|(PMBUS_CMD_BF_ENABLE<<0))\

#define CMD_C0_TO_C7_BITS_MASK  (Uint8)((PMBUS_CMD_C0_ENABLE<<7)|(PMBUS_CMD_C1_ENABLE<<6)|(PMBUS_CMD_C2_ENABLE<<5)|(PMBUS_CMD_C3_ENABLE<<4)|\
							   	   	    (PMBUS_CMD_C4_ENABLE<<3)|(PMBUS_CMD_C5_ENABLE<<2)|(PMBUS_CMD_C6_ENABLE<<1)|(PMBUS_CMD_C7_ENABLE<<0))\

#define CMD_C8_TO_CF_BITS_MASK  (Uint8)((PMBUS_CMD_C8_ENABLE<<7)|(PMBUS_CMD_C9_ENABLE<<6)|(PMBUS_CMD_CA_ENABLE<<5)|(PMBUS_CMD_CB_ENABLE<<4)|\
								 	 	(PMBUS_CMD_CC_ENABLE<<3)|(PMBUS_CMD_CD_ENABLE<<2)|(PMBUS_CMD_CE_ENABLE<<1)|(PMBUS_CMD_CF_ENABLE<<0))\

#define CMD_D0_TO_D7_BITS_MASK  (Uint8)((PMBUS_CMD_D0_ENABLE<<7)|(PMBUS_CMD_D1_ENABLE<<6)|(PMBUS_CMD_D2_ENABLE<<5)|(PMBUS_CMD_D3_ENABLE<<4)|\
							   	   	    (PMBUS_CMD_D4_ENABLE<<3)|(PMBUS_CMD_D5_ENABLE<<2)|(PMBUS_CMD_D6_ENABLE<<1)|(PMBUS_CMD_D7_ENABLE<<0))\

#define CMD_D8_TO_DF_BITS_MASK  (Uint8)((PMBUS_CMD_D8_ENABLE<<7)|(PMBUS_CMD_D9_ENABLE<<6)|(PMBUS_CMD_DA_ENABLE<<5)|(PMBUS_CMD_DB_ENABLE<<4)|\
								 	 	(PMBUS_CMD_DC_ENABLE<<3)|(PMBUS_CMD_DD_ENABLE<<2)|(PMBUS_CMD_DE_ENABLE<<1)|(PMBUS_CMD_DF_ENABLE<<0))\

#define CMD_E0_TO_E7_BITS_MASK  (Uint8)((PMBUS_CMD_E0_ENABLE<<7)|(PMBUS_CMD_E1_ENABLE<<6)|(PMBUS_CMD_E2_ENABLE<<5)|(PMBUS_CMD_E3_ENABLE<<4)|\
							   	   	    (PMBUS_CMD_E4_ENABLE<<3)|(PMBUS_CMD_E5_ENABLE<<2)|(PMBUS_CMD_E6_ENABLE<<1)|(PMBUS_CMD_E7_ENABLE<<0))\

#define CMD_E8_TO_EF_BITS_MASK  (Uint8)((PMBUS_CMD_E8_ENABLE<<7)|(PMBUS_CMD_E9_ENABLE<<6)|(PMBUS_CMD_EA_ENABLE<<5)|(PMBUS_CMD_EB_ENABLE<<4)|\
								 	 	(PMBUS_CMD_EC_ENABLE<<3)|(PMBUS_CMD_ED_ENABLE<<2)|(PMBUS_CMD_EE_ENABLE<<1)|(PMBUS_CMD_EF_ENABLE<<0))\

#define CMD_F0_TO_F7_BITS_MASK  (Uint8)((PMBUS_CMD_F0_ENABLE<<7)|(PMBUS_CMD_F1_ENABLE<<6)|(PMBUS_CMD_F2_ENABLE<<5)|(PMBUS_CMD_F3_ENABLE<<4)|\
							   	   	    (PMBUS_CMD_F4_ENABLE<<3)|(PMBUS_CMD_F5_ENABLE<<2)|(PMBUS_CMD_F6_ENABLE<<1)|(PMBUS_CMD_F7_ENABLE<<0))\

#define CMD_F8_TO_FF_BITS_MASK  (Uint8)((PMBUS_CMD_F8_ENABLE<<7)|(PMBUS_CMD_F9_ENABLE<<6)|(PMBUS_CMD_FA_ENABLE<<5)|(PMBUS_CMD_FB_ENABLE<<4)|\
								 	 	(PMBUS_CMD_FC_ENABLE<<3)|(PMBUS_CMD_FD_ENABLE<<2)|(PMBUS_CMD_FE_ENABLE<<1)|(PMBUS_CMD_FF_ENABLE<<0))\



////////////////////////////////////////////////////////////////
//the commands that shows bit masking of which PMBUS commands
//are supported
//CMD_DCDC_PAGED, CMD_DCDC_NONPAGED, CMD_PFC
//
//cmd-->lower nibble
// #     0123 4567    89AB CDEF
//higher
//nibble
//0    0b0000 0000, 0b0000 0000, command codes from 0x00 to 0x0F
//1    0b0000 0000, 0b0000 0000, command codes from 0x10 to 0x1F
//2    0b0000 0000, 0b0000 0000, command codes from 0x20 to 0x2F
//3    0b0000 0000, 0b0000 0000, command codes from 0x30 to 0x3F
//4    0b0000 0000, 0b0000 0000, command codes from 0x40 to 0x4F
//5    0b0000 0000, 0b0000 0000, command codes from 0x50 to 0x5F
//6    0b0000 0000, 0b0000 0000, command codes from 0x60 to 0x6F
//7    0b0000 0000, 0b0000 0000, command codes from 0x70 to 0x7F
//8    0b0000 0000, 0b0000 0000, command codes from 0x80 to 0x8F
//9    0b0000 0000, 0b0000 0000, command codes from 0x90 to 0x9F
//A    0b0000 0000, 0b0000 0000, command codes from 0xA0 to 0xAF
//B    0b0000 0000, 0b0000 0000, command codes from 0xB0 to 0xBF
//C    0b0000 0000, 0b0000 0000, command codes from 0xC0 to 0xCF
//D    0b0000 0000, 0b0000 0000, command codes from 0xD0 to 0xDF
//E    0b0000 0000, 0b0000 0000, command codes from 0xE0 to 0xEF
//F    0b0000 0000, 0b0000 0000, command codes from 0xF0 to 0xFF
/*
#define CMD_DCDC_PAGED  \
 						   {0x00, 0x00, \
                            0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00  \
							}

#define CMD_DCDC_NONPAGED  \
                           {0x10, 0x00, \
                            0x60, 0x00, \
                            0xC0, 0x00, \
                            0x10, 0x00, \
                            0x82, 0x01, \
                            0x00, 0x10, \
                            0x00, 0x00, \
                            0x00, 0xC0, \
                            0x00, 0x1C, \
                            0x04, 0xFE, \
                            0x00, 0x04, \
                            0x00, 0x00, \
                            0x00, 0x00, \
                            0x00, 0x60, \
                            0x3F, 0x00, \
                            0xA8, 0x3C \
                            }
*/
#define CMD_DCDC_PAGED  \
 						   {0x00, 0x00, \
                            0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00, \
							0x00, 0x00  \
							}

#define CMD_DCDC_NONPAGED  \
                           {CMD_00_TO_07_BITS_MASK, CMD_08_TO_0F_BITS_MASK, \
							CMD_10_TO_17_BITS_MASK, CMD_18_TO_1F_BITS_MASK, \
							CMD_20_TO_27_BITS_MASK, CMD_28_TO_2F_BITS_MASK, \
							CMD_30_TO_37_BITS_MASK, CMD_38_TO_3F_BITS_MASK, \
							CMD_40_TO_47_BITS_MASK, CMD_48_TO_4F_BITS_MASK, \
							CMD_50_TO_57_BITS_MASK, CMD_58_TO_5F_BITS_MASK, \
							CMD_60_TO_67_BITS_MASK, CMD_68_TO_6F_BITS_MASK, \
							CMD_70_TO_77_BITS_MASK, CMD_78_TO_7F_BITS_MASK, \
							CMD_80_TO_87_BITS_MASK, CMD_88_TO_8F_BITS_MASK, \
							CMD_90_TO_97_BITS_MASK, CMD_98_TO_9F_BITS_MASK, \
							CMD_A0_TO_A7_BITS_MASK, CMD_A8_TO_AF_BITS_MASK, \
							CMD_B0_TO_B7_BITS_MASK, CMD_B8_TO_BF_BITS_MASK, \
							CMD_C0_TO_C7_BITS_MASK, CMD_C8_TO_CF_BITS_MASK, \
							CMD_D0_TO_D7_BITS_MASK, CMD_D8_TO_DF_BITS_MASK, \
							CMD_E0_TO_E7_BITS_MASK, CMD_E8_TO_EF_BITS_MASK, \
							CMD_F0_TO_F7_BITS_MASK, CMD_F8_TO_FF_BITS_MASK, \
                            }

const Uint8 cmd_dcdc_paged[32]     = CMD_DCDC_PAGED;
const Uint8 cmd_dcdc_nonpaged[32]  = CMD_DCDC_NONPAGED;


Uint8 pmbus_read_write_message(Uint8 pmbus_read)
{
	return pmbus_commands[pmbus_index_array[pmbus_buffer[0]]].pmbus_read_write_function_pointer(pmbus_read);
}

